### ISSUE TITLE
1.2.0 changes QnAMaker Dialog subscriptionKey to authKey which is a breaking API change

### ISSUE THREAD

**Issue by avoidwork** [microsoft/BotBuilder-CognitiveServices#101]
Hi,

The commit https://github.com/Microsoft/BotBuilder-CognitiveServices/commit/a62a4e2d4f89c59469388c0852cfcf3c29bc4a39 introduced an API change such that any bots generated in Azure today are broken upon deployment, and there's no useful error logged to explain why all requests are 401.

This should've been 2.0.0

A bot created in Azure today will have `^1.1.0` for this project, such that `1.2.0` with the API change will be installed; this is the code the bot will have:

```javascript
var recognizer = new builder_cognitiveservices.QnAMakerRecognizer({
                knowledgeBaseId: process.env.QnAKnowledgebaseId,
    subscriptionKey: process.env.QnASubscriptionKey});
```

**Comment by avoidwork** [comment]
Yes, but all existing bots that can be reinstalled will have this issue. that's why it needs to be 2.0.0, the way it is now is effectively a surprised forced upgrade / refactor.

**Comment by avoidwork** [comment]
There's also no git tags on this repo, making it very very hard to track changes.

**Comment by c-h-russell-walker** [comment]
Related to what @avoidwork said above not only would git tags be helpful to investigate differences but a changelog would be helpful too - thanks!

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
