### ISSUE TITLE
Port number for cognitive services

### ISSUE THREAD

**Issue by Wayne-Shen** [Microsoft/BotBuilder-CognitiveServices#103]
Hello,

Our company is behind the corporate proxy, which port numbers (like 80,443) should we open if we  want to use cognitive services and bot service diretline APIs?

Thanks!
Wayne

**Comment by EricDahlvang** [comment]
Ports 80 and 443 are it.  The calls are just standard REST api calls, there are no special pots involved.

**Comment by Wayne-Shen** [comment]
Thanks!
