### ISSUE TITLE
QnAMaker Metadata filter can not be used

### ISSUE THREAD

**Issue by nagatatomoaki** [microsoft/BotBuilder-CognitiveServices#105]
QnAMakerService.cs uses https://westus.api.cognitive.microsoft.com/qnamaker/v2.0 instead of https://westus.api.cognitive.microsoft.com/qnamaker/v4.0

**Comment by jusso-dev** [comment]
+1 to this getting resolved, till then i stick with my own solution.

**Comment by stevengum97** [comment]
I'm not a C# dev but can't you just do the following?

```cs
[QnAMaker("set yout subscription key here", "set your kbid here", 
    "westus.api.cognitive.microsoft.com/qnamaker/v4.0")]
```

Or

```cs
[QnAMaker("set yout subscription key here", "set your kbid here",
    EndpointHostName: "westus.api.cognitive.microsoft.com/qnamaker/v4.0")] // Or EndpointHostName="..."
```

[Lines 110-116](https://github.com/Microsoft/BotBuilder-CognitiveServices/blob/master/CSharp/Library/QnAMaker/QnAMaker/QnAMakerService/QnAMakerService.cs#L110L116) of [QnAMakerService.cs](https://github.com/Microsoft/BotBuilder-CognitiveServices/blob/master/CSharp/Library/QnAMaker/QnAMaker/QnAMakerService/QnAMakerService.cs) indicate that it defaults to v2.0 as long as you don't provide anything. [Lines 117-145](https://github.com/Microsoft/BotBuilder-CognitiveServices/blob/master/CSharp/Library/QnAMaker/QnAMaker/QnAMakerService/QnAMakerService.cs#L117L145) show that it will build the v4 endpoint based on the `EndpointHostName` attribute.


Comments from [sample](https://github.com/Microsoft/BotBuilder-CognitiveServices/blob/master/CSharp/Samples/QnAMaker/SimpleQnABot/Dialogs/SimpleQnADialog.cs#L7L8):

```cs
    // Below method uses the V2 APIs : https://aka.ms/qnamaker-v2-apis. 
    // To use V4 stack, you also need to add the Endpoint hostname to the parameters below : https://aka.ms/qnamaker-v4-apis
```

**Comment by jusso-dev** [comment]
Yes you can, but that's not going to allow us to take advantage of the new metadata objects in the json, but as I said it's not the end of the world, as you can just roll your own solution, it would just be nice if the library had that support.

**Comment by Rykimaruh** [comment]
Is there any update to this? we ever getting metadata in the library?

**Comment by tulasim88** [comment]
Hi there, you can see details here for using metadata filters by just calling the generate answer API: 
https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/metadata-generateanswer-usage

Hope that answers your question.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
