### ISSUE TITLE
QnAMaker v4 and Feedback

### ISSUE THREAD

**Issue by nrobert** [Microsoft/BotBuilder-CognitiveServices#106]
In the Generally Available version of QnAMaker (and v4 API), is there any equivalent of the previous "train" operations which provided feedbacks to the search system? Or is it dropped due to the change of Search system?

This operation disappeared from the v4 API [here](https://westus.dev.cognitive.microsoft.com/docs/services/5a93fcf85b4ccd136866eb37/operations/5ac266295b4ccd1554da75ff)

Original question from a StackOverflow user: https://stackoverflow.com/questions/50401507/training-qna-maker-with-api-v4-0

**Comment by justincarlson** [comment]
Same question/issue.  Will be watching for updates.

**Comment by faraazc** [comment]
Same question .Please Microsoft respond to this

**Comment by Arvlun** [comment]
Same question.

**Comment by nrobert** [comment]
@JasonSowers , any chance we got an update from someone on Microsoft side about this one? Thanks!

**Comment by stevengum97** [comment]
@pchoudhari, can you provide some guidance on this API?

**Comment by pchoudhari** [comment]
We do not have the train API in V4. We are re-thinking this feature and will re-enable an advanced version in a future release.

**Comment by jjgriff93** [comment]
Hi all, I have a customer who is relying on this feature to continually train their QnA system, I think this being dropped has not been communicated nearly clear enough. Can we have a view of when this will be re-enabled please?

**Comment by pchoudhari** [comment]
Hi,

We would really love to hear how the customer is using the Train API. Can you drop a mail to qnamakersupport@microsoft.com?

The Train API in its current form isn't very useful, hence we are re-thinking on how to make it more effective. I don't have timeline, but we are actively working on this.

**Comment by PhantasmNZ** [comment]
qnamaker without the active learning capability is effectively a dead solution to us - it seems in thw GA you have replaced the whole point of machine learning (using real life examples to train the model) with a human "data champion" who tries to imagine every singe way a question might be phrased and add it to the web interface. 

the active learning should allow the AI to improve iteself over time by adjusting the training model (just like it does when you select via the interface) based on the correct response to a "top n" set of answers where the scores are not obvious. 

removing the train feature at runtime completely removes the intelligence from the system

Way to go... release a useful beta product and then kill it at GA by removing the very thing that makes it more useful than any keyword based q&a product.   

Very disappointed in this. Emailed.   

Hopefully you either fix this or Amazon/Google/IBM get there first....

**Comment by pchoudhari** [comment]
@PhantasmNZ , your feedback is valuable, and we do understand the importance of the active learning feature.

What we observed is that, the way users were using the Train API was incorrect. Many time they simply wanted to update their knowledge base. Even when they actually gave the user feedback to the Train API, the system wasn't learning very well.

The challenges we are trying to solve is to learn a more generic intent from the feedback and prevent fraud.

We are confident that the revised version of Active learning will be much more robust.

**Comment by beatgates** [comment]
@pchoudhari Thanks for your update. I believe most people would like to see some roadmap for this feature rather than being left in the dark...

**Comment by PhantasmNZ** [comment]
@pchoudhari Thanks for you comment - Do you have a timeframe?

I'd rather have "not learning very well" than "not learning at all"

Thanks

**Comment by faraazc** [comment]
@pchoudhari I completely agree with @PhantasmNZ's point that "qnamaker without the active learning capability is effectively a dead solution". We have an implementation which relies heavily on train API and this thing missing in GA is impacting badly. Please share the timeline when this will be added back and we can promise our customers accordingly. Removing API all of a sudden without notice is a serious concern and a completely unacceptable approach.

**Comment by PhantasmNZ** [comment]
@pchoudhari @stevengum why is this issue closed by the way? (only just noticed) - can we open it again or should it be logged as a new issue?

**Comment by nrobert** [comment]
Keep in mind that preview version is preview... so big changes can happen. You can still make it "learn" by adding question synonyms.

Did you have real feedbacks of the train operation?

**Comment by PhantasmNZ** [comment]
not realistic ... see my original post.

The whole point of an AI system is that you can improve the outcome by training the system - not by feeding it every possible answer. 

active learning is a must - trying to create every single question synonym is far from "learning"
quietly dropping a key feature without even a word or mention is unacceptable.

**Comment by nrobert** [comment]
I agree but I was just trying to point to my main question which is: does anyone knows what was done behind this train API?

It looks like you hope it was doing special things, but do you have any feedbacks of what this operation was bringing?

**Comment by PhantasmNZ** [comment]
Added a new issue #123 since this one is closed.

**Comment by sshradha** [comment]
@PhantasmNZ and @faraazc  Have you tried QnA Maker's active learning which has been enabled recently as per MS docs. 
https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/improve-knowledge-base

We have also been waiting for this feature so I am interested in knowing its feedback.

**Comment by faraazc** [comment]
@sshradha Thanks for re-enabling yet to try. I will keep you posted on this.
