### ISSUE TITLE
Returning confidence of 100 for numeric requests

### ISSUE THREAD

**Issue by snaxxi** [Microsoft/BotBuilder-CognitiveServices#107]
I have some answers in my knowledge base which include steps to resolve their question.

On sending requests which include the numbers from the answer,  i get a confidence score of 100 to the above mentioned answer even if there is no matching context.
> can a grown man eat more than 2 lemons?

> 1. do the first thing, to make sure the second step in this example works 
> 2. do this after to resolve the problem your question indicates

**Comment by stevengum97** [comment]
@snaxxi, can you provide some examples of the correct behavior you're expecting? If I understand correctly, the first quote is the question and the second is the answer?

**Comment by snaxxi** [comment]
@stevengum97 
Yes, the first quote is the question and the second the answer.
I'm expecting it to have a score of way below 100 because there is no matching context other than a number. Just for clarification: The question is made up and not linked to any anwser or has any context with the question of the answer.

FYI i already opened a Support Ticket in Azure, so we might close this issue.
