### ISSUE TITLE
QnA Dialog validation request

### ISSUE THREAD

**Issue by srozga** [microsoft/BotBuilder-CognitiveServices#108]
The QnA Dialog accepts the service config with the score threshold. I spent an hour this am struggling with the code because I could see through fiddler that my QnA KB was returning results with a score of 100 but the dialog was displaying a no match found message. Turns out, the score threshold must be from 0-1.0 because the code has a score/100 in there. It would be helpful to receive an ArgumentException or something similar when the threshold is set to a number greater than 1.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
