### ISSUE TITLE
No access to /train endpoint

### ISSUE THREAD

**Issue by johnjkk** [Microsoft/BotBuilder-CognitiveServices#110]
In the code example it shows how to train qnamaker with /train endpoint.

this.kbUriForTraining = 'https://' + hostName + '/qnamaker/knowledgebases/' + this.options.knowledgeBaseId + '/' + qnaTrainApi;

However, this does not work.

This returns 405 Method Not Allowed.
I have tried all possible methods: POST, PUT, PATCH, GET etc

None of them work. They all fail with 405.

**Comment by snaxxi** [comment]
#106

**Comment by fanidamj** [comment]
We do not have the train API in V4. We are re-thinking this feature and will re-enable an advanced version in a future release. You can follow up with #106 issue.
