### ISSUE TITLE
QnAMaker nodejs samples are for Bot sdk V3 or V4?

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/BotBuilder-CognitiveServices#111]
I am looking at very promising concepts & samples here [https://github.com/Microsoft/BotBuilder-CognitiveServices/tree/master/Node/samples/QnAMaker](https://github.com/Microsoft/BotBuilder-CognitiveServices/tree/master/Node/samples/QnAMaker) but confused if I can use this in my V3 BOT.

I would appreciate any help. Thank you.

**Comment by JasonSowers** [comment]
These samples are v3 samples

**Comment by rjgmail88** [comment]
Thanks @JasonSowers
