### ISSUE TITLE
Version Upgrade

### ISSUE THREAD

**Issue by dkbhadeshiya** [microsoft/BotBuilder-CognitiveServices#116]
Hello guys, 
As of the Microsoft Build 2018, QnAMaker gets an stable release. However when I see libraries, I see that it has not been updated for the latest version. 
Any idea when can we get updated version of the library for latest QnAMaker? 

Thanks

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
