### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by hilvarenbeek** [Microsoft/BotBuilder-CognitiveServices#117]
QnAMakerWithWithCustomTools should be QnAMakerWithCustomTools (double With removed)

**Comment by hilvarenbeek** [comment]
This is regarding https://github.com/Microsoft/BotBuilder-CognitiveServices/blob/master/Node/samples/QnAMaker/README.md (as there are more READMEs in the project)

**Comment by stevengum** [comment]
Fixed with #118, thank you for reporting this!
