### ISSUE TITLE
There is no API for the "train" function and no option to use "active learning".

### ISSUE THREAD

**Issue by PhantasmNZ** [microsoft/BotBuilder-CognitiveServices#123]
Adding a new issue as the previous ones have been inexplicably closed without addressing the issue further than "we removed it and we're thinking about how to re-add it"

https://github.com/Microsoft/BotBuilder-CognitiveServices/issues/106
https://github.com/Microsoft/BotBuilder-CognitiveServices/issues/110
(which says follow up with the #106 issue, that's also closed)

In order to build an intelligent q&a bot, the ability to have the bot learn from actual user inputs is crucial. There are two approaches that could be used here - either have an interface in the management tool that shows all (or maybe lower confidence) utterances and allow the admin to select the correct response to train the model (just like you can with LUIS), or, which is in may deployment scenarios, the most appropriate (typically when you are using the bot with knowledge workers more than when you are using it with the public) - have  the user select the most appropriate answer. 

The AI algorithm then has positive training samples to run against the model which can then tune the matching to the appropriate intent(/answer). 

A common deployment scenario for QnAMaker would be to have a company knowledgebase that is used both internally (say by a contact centre) and externally (on a website).  The internal staff have the experience to pick the best response from 3 or more options to help train the model - the website however may only return a single option. 

Not allowing training by example and "active learning" means this tool is missing a key aspect that is needed to move from keyword searching to AI based knowledge management.  Having some discussion and or roadmap for this feature that (whilst it may not have been as efficient or effective as it could have been) was promoted in most recent beta phases as a key feature and continues to be promoted in official MS - but non-functional - documentation, examples and tutorials around the web.

Please could we have some detail and timeline about the re-introduction of the Train and Active Learning API features in QnA Maker.

**Comment by EricDahlvang** [comment]
Hi @PhantasmNZ 

Thank you for taking the time to open this issue, and provide feedback.  We apologize that the other issues have been closed prematurely.  We will leave this open as an enhancement/feature request until we have a more definitive and publicly available plan for Train and Active Learning in qnamaker.

**Comment by petmat** [comment]
Hi @EricDahlvang 

Is there any update on this? We are dependent on the Train API and so far have not migrated from the Preview to GA because of it's absence. But the deadline for migrating is closing. If I'm not mistaken the Preview is only available until 7th of November. So is there any hope for continuing the use of the Train API? Or do we simply have to drop active learning altogether?

You've previously said that you will re-enable an advanced version of this feature in a future release but can you give us any estimate on when it would be? We were really hoping it would have been before the Preview version is shut down. Alternately if you cannot release a new version of Train API then maybe could you extend the sustaining of the Preview version?

**Comment by jjgriff93** [comment]
I would also appreciate an update on this issue please

**Comment by EricDahlvang** [comment]
This is being worked on, but there is no timeline available yet.

**Comment by PhantasmNZ** [comment]
Looks like https://github.com/MicrosoftDocs/azure-docs/issues/10147 also got inexplicably closed without a proper answer.

Come on Microsoft this is ludicrous - how about a straight answer so that your PAYING CUSTOMERS can plan properly....

**Comment by pchoudhari** [comment]
Hi,

We should have a date to announce soon to release the train feature. Also, we are likely to extend the preview deadline.

**Comment by petmat** [comment]
@pchoudhari Sorry to be constantly asking. I'm sure you're working hard on this, but with just a little over a week before the current preview deadline (November 7th) could you please give us anymore information about the train feature and more importantly about will the preview deadline be extended? We are in the process of deciding if we need to start migrating to GA immediately (and lose the train feature) or still stay with preview.

**Comment by PhantasmNZ** [comment]
If MS would simply provide proper information, we wouldn't have to be constantly asking.  Come on guys - you want us to use this stuff - just give us some straight talking answers....

**Comment by pchoudhari** [comment]
Hi,

We are targeting first quarter of CY19 to release the training feature back into the GA stack.

**Comment by petmat** [comment]
Thank you for announcing the target schedule! Will the preview deadline also be extended to the end of the Q1?

**Comment by petmat** [comment]
@pchoudhari Please can you give information about whether the preview will be extended or does it end tomorrow 7th November like previously was announced?

**Comment by pchoudhari** [comment]
We will extend the preview. You can expect an announcement shortly.

**Comment by JulienM28** [comment]
How can I use the preview?

**Comment by dcbrown16** [comment]
@pchoudhari, active learning is now enabled in the current verison. Will we be able to interact with it via API as well?

**Comment by pchoudhari** [comment]
@dcbrown16 , see https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/improve-knowledge-base . Primarily, we have introduced the Train API to give explicit feedback for active learning.

**Comment by dcbrown16** [comment]
Thanks @pchoudhari, I actually opened a documentation request there as well as the position and usage of the Train API isn't very clear from the current small example. There is a second feedback item to the same effect already as well.
https://github.com/MicrosoftDocs/azure-docs/issues/24629
Could you help @diberry work to clarify how the API is used with active learning?

**Comment by sshradha** [comment]
@petmat  Have you tried QnA Maker's active learning which has been enabled recently as per MS docs.
https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/improve-knowledge-base

We have also been waiting for this feature so I am interested in knowing its feedback.

**Comment by petmat** [comment]
@sshradha We are in the process of implementing active learning for our chatbots. So far it has been promising. It's different than active learning was in preview but not at all in a bad way.

I might be able to give better feedback as things progress.

**Comment by diberry** [comment]
@petmat @sshradha @dcbrown16 @pchoudhari @tulasim88 @EricDahlvang

I understand the active learning documentation, both inside the QnA Maker docs, and the Bot Framework docs needs more information. I'm interested to see what @petmat learned. If anyone else has general or specific learnings - please share. #in-progress

**Comment by sshradha** [comment]
@petmat @diberry 
Ours is also a FAQ bot that has been built using MS bot framework and QnA Maker. 
I had enabled Active learning yesterday for both Production and Dev QnA Maker service. But i am not seeing any suggestions. I have been waiting when the system shall start showing suggestions because bot is being used continuously since last evening.
So basically I am interested in both the features of Active learning:
1. How intelligent it is in showing automatic suggestions based on user queries which can be accepted as alternate utterances.
2. Train API. We have not implemented this yet.

I will also share my feedback and findings.

Thanks.
Shradha

**Comment by diberry** [comment]
@sshradha You did [turn on active learning](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/improve-knowledge-base#turn-on-active-learning), yes?

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
