### ISSUE TITLE
How to have multiple QnA recognizer on same Bot

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/BotBuilder-CognitiveServices#124]
I have a BOT with 1 LUIS recognizer and for QnA I'm making explicit request call to get an answer. After looking into this repo I see now I can use following code to have one more recognizer as QnA

```
var recognizer = new cognitiveservices.QnAMakerRecognizer({
	knowledgeBaseId: 'set your kbid here', 
	authKey: 'set your authorization key here',
	top: 4});
```  

I was wondering what to do if I have multiple QnA apps? How can I have 1 luis app and 3 QnA's under the same Bot hood.?

**Comment by rjgmail88** [comment]
@stevengum , could you please help on this too?

**Comment by fanidamj** [comment]
You can integrate multiple LUIS apps and QnA services with the [Dispatch tool.](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=csaddref%2Ccsbotconfig#integrate-multiple-luis-apps-and-qna-services-with-the-dispatch-tool) The documentation on [Dispatch](https://github.com/Microsoft/botbuilder-tools/tree/master/Dispatch) will also be helpful. Here is another example on [StackOverFlow.](https://stackoverflow.com/questions/50132206/multiple-qna-service-in-one-bot-using-c-sharp)

**Comment by rjgmail88** [comment]
Hi @fanidamj ,

I was aware of Dispatch tool but it's not GA yet. Also, the example you share is in C#. Can you suggesr nodejs one? where BotBuilder-CognitiveServices module is used .

**Comment by fanidamj** [comment]
@rjgmail88 Unfortunately we don't have the module supporting this in V3. The only solution is to manually use the logic of Dispatch tool used in V4.
