### ISSUE TITLE
QnA Maker General Update Service returning 3 answers despite top 1 is being passed.

### ISSUE THREAD

**Issue by mutanttech** [Microsoft/BotBuilder-CognitiveServices#126]
I am updating my application from **QnA Maker Preview to QnA Maker GA**, I have migrated KB to new QnA Maker Service and everything is setup.

The problem is while testing I found that one of the questions asked from bot was returning the Suggestions of close questions:
ex: Did you mean:
- Option 1
- Option 2
- Option 3

**And when I checked the response returned from QnA Maker Service it has 3 answers and each having score 0.98 and alternate questions.**

I checked the Cognitive Services code and found that there is a method IsConfidentAnswer which does following checks:
 ```
protected virtual bool IsConfidentAnswer(QnAMakerResults qnaMakerResults)
        {
            if (qnaMakerResults.Answers.Count <= 1 || qnaMakerResults.Answers.First().Score >= QnAMakerHighConfidenceScoreThreshold)
            {
                return true;
            }

            if (qnaMakerResults.Answers[0].Score - qnaMakerResults.Answers[1].Score > QnAMakerHighConfidenceDeltaThreshold)
            {
                return true;
            }

            return false;
        }
```

And in QnaMakerDialog.cs files under MessageReceivedAsync method we have below code:
```
public async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
        {
            var message = await argument;
            
            if (message != null && !string.IsNullOrEmpty(message.Text))
            {
                var tasks = this.services.Select(s => s.QueryServiceAsync(message.Text)).ToArray();
                await Task.WhenAll(tasks);

                if (tasks.Any())
                {
                    var sendDefaultMessageAndWait = true;
                    qnaMakerResults = tasks.FirstOrDefault(x => x.Result.ServiceCfg != null)?.Result;
                    if (tasks.Count(x => x.Result.Answers?.Count > 0) > 0)
                    {
                        var maxValue = tasks.Max(x => x.Result.Answers[0].Score);
                        qnaMakerResults = tasks.First(x => x.Result.Answers[0].Score == maxValue).Result;

                        if (qnaMakerResults != null && qnaMakerResults.Answers != null && qnaMakerResults.Answers.Count > 0)
                        {
                            if (this.IsConfidentAnswer(qnaMakerResults))
                            {
                                await this.RespondFromQnAMakerResultAsync(context, message, qnaMakerResults);
                                await this.DefaultWaitNextMessageAsync(context, message, qnaMakerResults);
                            }
                            else
                            {
                                feedbackRecord = new FeedbackRecord { UserId = message.From.Id, UserQuestion = message.Text };
                                await this.QnAFeedbackStepAsync(context, qnaMakerResults);
                            }

                            sendDefaultMessageAndWait = false;
                        }
                    }

                    if (sendDefaultMessageAndWait)
                    {
                        await context.PostAsync(qnaMakerResults.ServiceCfg.DefaultMessage);
                        await this.DefaultWaitNextMessageAsync(context, message, qnaMakerResults);
                    }
                }
            }
        }
  
```
Inside IsConfidentAnswer method answer count is hardcoded to <= 1 and  hard coded values for constants.
 ```
private const double QnAMakerHighConfidenceScoreThreshold = 0.99;
private const double QnAMakerHighConfidenceDeltaThreshold = 0.20;
```

Due to answers count is 3 with all having 0.98 score returned from QnA Service, IsConfidentAnswer evaluates to false. And feedbackStep is called which shows a Prompt Dialog.

The problem  is when I ask same question on Preview Service, have same utterance/questions, it returns one response and options are not displayed. But when I ask questions from GA service, multiple answers are returned.

**I am not sure what is the significance of top 1 in QnAMakerAttribute Constructor, where default value is already 1.**

 ```
public QnAMakerAttribute(string authKey, string knowledgebaseId, string defaultMessage = null, double scoreThreshold = 0.3, int top = 1, string endpointHostName = null)
        {
            if (string.IsNullOrEmpty(defaultMessage))
            {
                defaultMessage = Resource.Resource.defaultMessage;
            }

            SetField.NotNull(out this.AuthKey, nameof(authKey), authKey);
            SetField.NotNull(out this.KnowledgebaseId, nameof(knowledgebaseId), knowledgebaseId);
            SetField.NotNull(out this.DefaultMessage, nameof(defaultMessage), defaultMessage);
            this.ScoreThreshold = scoreThreshold;
            this.EndpointHostName = endpointHostName;
            this.Top = top;
        }
```

**I think top should be honored by the service and also what ever constants are taken, give user the flexibility to configure the values. Please let me know what to do?**

**Comment by bkjawal** [comment]
Facing same issue:-(

**Comment by mutanttech** [comment]
@fanidamj, Please let me know what should be next steps for me. When can I expect some update about above issue. Thanks..

**Comment by fanidamj** [comment]
I'm working on this issue and will get back to you soon.

**Comment by mutanttech** [comment]
Thanks @nyxsys for your analysis. The problem is with same data the QnA Preview Service returns only one answer based on testing on API Console. Morever, I have debugged the code of package BotBuilder-CognitiveServices and found with QnA Preview only one answer is returned while QnA GA returns three. I am not sure why there is discrepancy.

**Comment by mutanttech** [comment]
@nyxsys, let me know what do you think, based on my previous comment.

**Comment by pchoudhari** [comment]
Hi,

This has been fixed with a new runtime roll out that is currently underway. Can you re-start your app service next week and check again?

**Comment by mutanttech** [comment]
@pchoudhari, I will follow your instructions and get back to you next week with updates. Thanks..

**Comment by mutanttech** [comment]
@pchoudhari, I have followed the instructions and this seems to working correctly now. Thanks a lot.
