### ISSUE TITLE
how can Bot read an Azure sql database for querying a question

### ISSUE THREAD

**Issue by gouravbeyondBGCM** [Microsoft/BotBuilder-CognitiveServices#131]
hi 

I have a bot , that has to answer questions from a big database , the on premise database is in MySql .
1. I have to connect or load data from Mysql to Azure Database / Blob 
2. Now I need my bot should answer questions from that Azure Database .

Can you please help me in that.

**Comment by jwiley84** [comment]
Hi Gourav! Closing this as the bot framework support team prefers "How-To" questions be asked on stackoverflow. For your questions, you'll find [Database Migration](https://docs.microsoft.com/en-us/azure/cosmos-db/import-data) helpful as well as [How to get my Bot to send back database info](https://stackoverflow.com/questions/50749293/how-do-i-get-a-bot-framework-bot-to-send-back-a-cell-of-a-database-if-i-type-in).
