### ISSUE TITLE
[QnA maker]Metadata to boost results

### ISSUE THREAD

**Issue by YutongTie-MSFT** [microsoft/BotBuilder-CognitiveServices#132]
How can metadata be used to boost results? Just to clarify I am using QnAMaker v4.0 and I have gotten strictFilters to work with metadata but I cannot get metadataBoost to work. I am wondering if that was only offered in v3.0 and not v4.0?

#https://github.com/MicrosoftDocs/azure-docs/issues/13046

**Comment by pchoudhari** [comment]
Hi,

We do not have the metadata boost feature in V4 APIs. Can you drop a mail to qnamakersupport@microsoft.com with details of how you use this feature, which can help prioritize enabling this feature in the future.

**Comment by YutongTie-MSFT** [comment]
@andrewwself Hi, can you please provide more details here?

**Comment by ds99jove** [comment]
We are also missing the metadataBoost feature. We would like the user to ask a question and if the answer returned contains the metadata "category: computer" then we would like to boost the next questions answers in that category. We do not want to use strictFilters as we do not want to limit subsequent answers to that category.

**Comment by stevospinks** [comment]
Are there any updates on this?
In the API it looks like this should be supported, but it doesn't seem to have any effect.

My JSON:
```
{
	"question": "Can I test metadata?",
	"top": 3,
	"metadataBoost": [
		{
			"name": "user_type",
			"value": "manager"
		}]
}
```

My response:
```
{
    "answers": [
        {
            "questions": [
                "Can I test the metadata?"
            ],
            "answer": "Yes, employee",
            "score": 98,
            "id": 122,
            "source": "Editorial",
            "metadata": [
                {
                    "name": "user_type",
                    "value": "employee"
                }
            ]
        },
        {
            "questions": [
                "Can I test the metadata?"
            ],
            "answer": "Yes, manager",
            "score": 98,
            "id": 123,
            "source": "Editorial",
            "metadata": [
                {
                    "name": "user_type",
                    "value": "manager"
                }
            ]
        },
        {
            "questions": [
                "Can I test the metadata?"
            ],
            "answer": "Yes, unknown user",
            "score": 98,
            "id": 124,
            "source": "Editorial",
            "metadata": []
        }
    ]
}
```

**Comment by stevospinks** [comment]
I emailed qnamakersupport@microsoft.com with my above comment and received this response:

> This feature is not available in v4.0(GA version).

I've asked whether there are any plans for this to be implemented in this or later versions, and will update if I receive a response

**Comment by pchoudhari** [comment]
Hi,

We don't have in our immediate roadmap to bring back metadata boost. However, as a workaround you can first call the strict filter and then if you receive no results then call the regular generate answer.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
