### ISSUE TITLE
Received a security vulnerability warning from our org:

### ISSUE THREAD

**Issue by wemiao** [Microsoft/BotBuilder-CognitiveServices#133]
can't paste the text easily from Outlook, so attaching an image:

![vulnerabilities](https://user-images.githubusercontent.com/16315883/44362045-af5bf100-a474-11e8-87b1-dac446158501.PNG)

**Comment by stevengum** [comment]
Closing as the original vulnerabilities show up via BotBuilder. An issue was filed there, Microsoft/Botbuilder#4706 and a accompanying PR to fix these vulnerabilities was merged in a little over two weeks ago (Microsoft/Botbuilder#4715). Once BotBuilder updates, and then Botbuilder-CognitiveServices undergoes a new release these vulnerability messages should go away.
