### ISSUE TITLE
[Node] TypeScript typings

### ISSUE THREAD

**Issue by afnan-ahmad** [microsoft/BotBuilder-CognitiveServices#135]
Hi,

The TypeScript typings file mentioned in **package.json** from the **./lib** directory actually does not exist at that location. I had to download the file and put it there manually. Also, this causes problems when using npm / yarn to fetch the packages.

Secondly, there seems to be a few typos in this file where **IQnAMakerResult** is incorrectly referred to as **IQnAMakerResults** in some places. A workaround is to manually fix those references. 

EDIT: The **"top"** parameter in **IQnAMakerOptions** was also misspelled as **"Top"** causing the parameter to have no effect on the recognizer. It is working fine after correcting the spelling.

EDIT: Submitted a PR (#136) addressing the above mentioned issues (except for npm related). Please review and merge.

EDIT: I have found another problem regarding **IQnAMakerOptions** is that the parameter **qnaThreshold**  does not have any effect on the responses being returned. (this one is not directly related to typings though, so would be opening a separate issue for this). See Issue #137 for details.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
