### ISSUE TITLE
[Question] How QnAMakerHighConfidenceDeltaThreshold value decided. 

### ISSUE THREAD

**Issue by aoueki** [Microsoft/BotBuilder-CognitiveServices#139]
I have the simple question about how and why QnAMakerHighConfidenceDeltaThreshold value（that is, 0.20）was determined in the code below.
 
https://github.com/Microsoft/BotBuilder-CognitiveServices/blob/7866f5a1bc970bdd0be341b9ba24c74067edf57c/CSharp/Library/QnAMaker/QnAMaker/QnAMakerDialog.cs#L56

Is there any reasons for 0.20 or the procedure that a developer followed to statistically or Mathematically determine this value? Why its not 0.21, 0.23, 0.25 but 0.20. 
 
If No Reason, it would be fine anyway. Any information would be helpful. Thank you.

**Comment by v-kydela** [comment]
@aoueki - I notice you closed this issue. Has it been resolved for you?
