### ISSUE TITLE
Add italian language support

### ISSUE THREAD

**Issue by lfongaroScp** [Microsoft/BotBuilder-CognitiveServices#144]
Hi,

Is it in plan to add the italian  translation for the string in the resource file?

**Comment by stevkan** [comment]
Hi @lfongaroScp, were you able to resolve this?

Looking over the Cognitive Services docs, they suggest Italian is already supported. [This doc](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-migrate-from-translator-speech-api#comparison-of-features) states the new speech service will support the same languages the Translator Speech API supports (being retired).

The full list of languages supported can be viewed [here](https://docs.microsoft.com/en-us/azure/cognitive-services/translator-speech/languages). Further information can be read [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/index) on the new Speech service and how to implement.

**Comment by stevkan** [comment]
Closing due to lack of response.
