### ISSUE TITLE
Reusing of HttpClient

### ISSUE THREAD

**Issue by jusso-dev** [Microsoft/BotBuilder-CognitiveServices#145]
The .NET SDK for the QnaMakerService class is not reusing HttpClient instances, which can lead to socket exhaustion, as discussed here - https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

The following methods that I found are implementing instances of the HttpClient in a using statement:

- QueryServiceAsync
- ActiveLearnAsync

I can see this being a massive problem, especially where the consuming client of the service is a Chatbot, as they are obviously very chatty (no pun intended).

Happy to submit a pull request to fix this, but there's a fair bit of work involved, such as DI as so on. 

Let me know your thoughts.

Cheers,
Justin

**Comment by JasonSowers** [comment]
Yes, if you would be willing to submit a pull request so we can review it that would be great.

**Comment by JasonSowers** [comment]
Closing this issue awaiting PR review #146
