### ISSUE TITLE
QnAMakerResults.ServiceCfg suggestion and QnAMakerDialog bug

### ISSUE THREAD

**Issue by mitkodi** [microsoft/BotBuilder-CognitiveServices#147]
1. I think that making ```QnAMakerResults.ServiceCfg``` publicly readable would allow us to customize ```QnAMakerDialog``` by overriding it instead of copying its code.
And I think that the same is true for```QnAMakerService.qnaInfo```. If it's publicly accessible we could add more info (by subclassing ```QnAMakerAttribute```) about the service (e.g. its language).
2. There is a bug in ```var maxValue = tasks.Max(x => x.Result.Answers[0].Score);``` (at line 99) which would lead to ```ArgumentOutOfRangeException``` if we're querying more than one service and one of them returns no answers.

P.S.
If you don't mind I could make a pull request for these small tweaks.

**Comment by cleemullins** [comment]
@mitkodi, if you're up for a PR, I think that would be great. Thanks! 

I'm hesitant on making the classes public, as it increases our overall surface area. This has implications for docs, samples, and other languages (C#, etc).  Certainly a PR for the bug fix seems like the right choice.

**Comment by cleemullins** [comment]
@mitkodi, to go a bit futher, if you're using the C# V4 SDK, this entire repo is pretty much obsolete. The QnA Maker classes have been brought directly into the relevant [C#](https://github.com/Microsoft/botbuilder-dotnet/tree/master/libraries/Microsoft.Bot.Builder.AI.QnA)/[JS](https://github.com/Microsoft/botbuilder-js/tree/master/libraries/botbuilder-ai/src) BotBuilder repos.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
