### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by hemachowdary** [Microsoft/BotBuilder-CognitiveServices#149]
Hi,
I am trying to work on QnA Maker Dialog.  I am not able to install [BotBuilder-CognitiveServices](https://www.npmjs.com/package/botbuilder-cognitiveservices) package. I am getting an error unexpected end of file. Attaching the screenshot of the same. please help on this.
![errorinstallation](https://user-images.githubusercontent.com/2978192/47833941-6359f080-ddc3-11e8-8c87-d5db4675447e.JPG)

**Comment by jwiley84** [comment]
Can you post the error log you recieved?

**Comment by hemachowdary** [comment]
After tweaking i figured out that the "unexpected end of file" error that I got is due to a problem in the cognitive services package. I tried with 3.19 version. It got installed without error. But I would like to know whether the current version of QnA maker has support for Active Learning or not? Please give me some info on that.

**Comment by jwiley84** [comment]
Hi @hemachowdary! The Cognitive Services packages are currently on release 4.1.5. It's concerning that you needed to use 3.19. Are you building a v3 bot? 
As for Active Learning, the GA version of QnA Maker does not have it, however, the team is currently looking into possible future reintegration. You can follow that progress [here](https://github.com/Microsoft/BotBuilder-CognitiveServices/issues/123).

**Comment by jwiley84** [comment]
Closing as original issue is resolved. Please follow the link in the earlier response to track the status of Active Learning.
