### ISSUE TITLE
is there an API for "Refresh Content" ?

### ISSUE THREAD

**Issue by dhinag** [Microsoft/BotBuilder-CognitiveServices#151]
I do not see any API that is available to "Refresh Content" as part of QnAMaker. I believe, even if there is an API to "Refresh Content", it may not work as we do not have api for "Train" ( #106 ). Is my understanding correct?

If that is the case, is it possible to let me know if "Refresh Content" api is in your roadmap or is there any other workaround ?

**Comment by stevkan** [comment]
@dhinag, can you elaborate on what you mean by "refresh content"? Do you mean refresh a kb, the contents of one, or something else?

**Comment by stevkan** [comment]
@dhinag, I'm looking into this and hopefully will have a response for you before too long.

**Comment by stevkan** [comment]
@dhinag, you can achieve this by making an update call against the knowledge base using the Update Knowledge Base API. You can read documentation [here](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/quickstarts/csharp#Update) on how to do so. This link is for building in C#, but there are instructions for Node, Java, and Python, as well.

When you make the call, your JSON body should be: {"add":{},"delete":{},"update":{**"urls":["your URL"**]}}

Hope of help!

**Comment by dhinag** [comment]
Thank you, Steven. I'll give this a try.
