### ISSUE TITLE
QnAMaker v4 Get unique ids generated by qna maker using the API

### ISSUE THREAD

**Issue by sahilsharmafrank** [Microsoft/BotBuilder-CognitiveServices#153]
In new qna maker v4 i am using the apis to create a new question i am able to create one but i donot get the back the unique id to update or delete the record. I am using `PATCH Update Knowledgebase` to add a new record/qna pair and `GET Operation details` to see if the operation succeed, But nowhere can i find the unique id. Can i have some pointers

**Comment by Zerryth** [comment]
@sahilsharmafrank you're correct in that when you do `PATCH Update Knowledgebase`, you get a response that takes the shape like the following:

```js
{
    "operationState": "...",
    "createdTimestamp": "2018-12-09T07:58:39Z",
    "lastActionTimestamp": "2018-12-09T07:58:39Z",
    "userId": "63exxxxxxxxxxxxxxxxxxxxxdxxxxbcf",
    "operationId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
}
```
Where the qnaId of the QnA Entity that was "updated" is not shown.
___
Right now it seems like you could use `GET Download Knowledgebase`, and it will return to you something like the shape of the following.

```js
{
    "qnaDocuments": [
        {
            "id": 1,
            "answer": "Answer",
            "source": "smartLightFAQ.tsv",
            "questions": [
                "Question"
            ],
            "metadata": [],
            "alternateQuestionClusters": []
        },
        {
            "id": 2,
            "answer": "Check the connection to the wall outlet to make sure it's plugged in properly.",
            "source": "smartLightFAQ.tsv",
            "questions": [
                "My Contoso smart light won't turn on.",
                "Light won't turn on."
            ],
            "metadata": [],
            "alternateQuestionClusters": []
        },
       // ...
    ]
}
```

**Note how it returns the questions within the QnA Entity, which has a unique qnaId ("`id`")**
___
If there is a more straight-forward way to do this with the QnA v4 API that I hear about, I'll update this thread
