### ISSUE TITLE
Alterations dont seem to work

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotBuilder-CognitiveServices#159]
I have put alteration list in my service...

When I ask a question with the origin word ( the question in qnamaker contains the word ) the score is high..
But when the same question is asked with the word alteration from original word's list, the score dramatically drops....

Are there any best practices or suggestions on how to make this work well?

**Comment by v-kydela** [comment]
Hi @ubreddy 

There is documentation about best practices [here](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/concepts/best-practices#use-synonyms).

Is that what you're looking for?

**Comment by v-kydela** [comment]
Do the scores increase after you train your LUIS app?

**Comment by ubreddy** [comment]
yes. If we use LUIS apps it works lot better...  synonyms work well there...
We are trying to get similar results from qnamaker with alterations  origin word question has score 70% and the question replaced with synonym has score 8%
which does not make the threshhold
Uday 

    On Thursday, 31 January, 2019, 10:38:46 PM IST, Kyle Delaney <notifications@github.com> wrote:  
 
 
Do the scores increase after you train your LUIS app?

**Comment by v-kydela** [comment]
Ah sorry, I meant to say QnAMaker, not LUIS. Do the scores improve if you train your QnAMaker app?

**Comment by ubreddy** [comment]
If I train with the question alternatives with synonyms replaced then the scores imporve...
e.g. I want to buy laptop  
laptop, notebook, note-book are synonyms
Scores are quite bad if I say I want to buy note-book...
But if I have alternate question trained, the scores are more are less in the range...
Uday 

    On Friday, 1 February, 2019, 12:09:33 AM IST, Kyle Delaney <notifications@github.com> wrote:  
 
 
Ah sorry, I meant to say QnAMaker, not LUIS. Do the scores improve if you train your QnAMaker app?

**Comment by v-kydela** [comment]
That's very interesting, @ubreddy 

Sorry for the delay. I think I understand now. May I ask how you're adding word alterations to your service? Are you using the [REST API](https://westus.dev.cognitive.microsoft.com/docs/services/5a93fcf85b4ccd136866eb37/operations/5ac266295b4ccd1554da75fd)? Are you sending the HTTP messages with a specific tool? Have you verified that the alterations have been successfully applied to your service by [downloading](https://westus.dev.cognitive.microsoft.com/docs/services/5a93fcf85b4ccd136866eb37/operations/5ac266295b4ccd1554da75fc) them?

**Comment by ubreddy** [comment]
Got resolved. Thanks to MS support. The solution was that the synonyms should be defined in lower case.Not sure why though!
Uday 

    On Thursday, 7 February, 2019, 5:39:31 AM IST, Kyle Delaney <notifications@github.com> wrote:  
 
 
That's very interesting, @ubreddy

Sorry for the delay. I think I understand now. May I ask how you're adding word alterations to your service? Are you using the REST API? Are you sending the HTTP messages with a specific tool? Have you verified that the alterations have been successfully applied to your service by downloading them?

**Comment by v-kydela** [comment]
Glad to hear your issue is fixed! I'm guessing internally the QnAMaker service must convert all queries to lower case but neglects to do that with alterations, so that could easily be a bug. Either way, I'll keep this solution in mind in case I encounter the issue again.

~ Kyle
