### ISSUE TITLE
QueryServiceAsync isn't really async - causes blocking

### ISSUE THREAD

**Issue by onovotny** [Microsoft/BotBuilder-CognitiveServices#16]
The implementation of QueryServiceAsync isn't really async. It has an `async` keyword on the method but no await statements. You must be getting a build warning on this saying that the code is running synchronously. This is causing code to block in paths that are unexpected.

https://github.com/Microsoft/BotBuilder-CognitiveServices/blob/90db6eadc0e0189203316e754f83dd93d2338ed8/CSharp/Library/QnAMaker/QnAMakerService/QnAMakerService.cs#L92

The underlying issue is that the code is using WebClient, which isn't async friendly. WebClient code should be removed in favor of HttpClient, which is async.

/cc @bdoodnauthBlueMetal

**Comment by bdoodnauthBlueMetal** [comment]
Please review fix posted in pull request https://github.com/Microsoft/BotBuilder-CognitiveServices/pull/18

**Comment by dasvictor** [comment]
Merged.
