### ISSUE TITLE
[QnA maker] confidence scores bad sorting 

### ISSUE THREAD

**Issue by JuanPabloSebey** [microsoft/BotBuilder-CognitiveServices#162]
When i ask for top 2 answers i get

Answer | Confidence
------------ | -------------
Answer 1 | 85
Answer 2 | 70

but when i ask for top 5 i get (exact same question)

Answer | Confidence
------------ | -------------
Answer 3 | 95
Answer 1 | 85
Answer 2 | 70
... | ...

The correct  answer is *Answer 3* but i only get it if i ask for more results.
In my real case i need a top 100 in order to get the correct answer.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
