### ISSUE TITLE
published only one >br> but qnamkaer adds another line break

### ISSUE THREAD

**Issue by paigeflourin** [Microsoft/BotBuilder-CognitiveServices#163]
I am using web api to publish the qnamaker and from my react app this is the answer portion of my publish string that i am passong backend:

`test<br> new line here<br><br>Howver this should ba a separate paragraph. jsdhuagdhc asuhduhuisnudh<br>new line<br><br>test paragraph<br>`

however in qnamaker, the published answer became like this

`test \n\nnew line here\n\n\nHowver this should ba a separate paragraph. jsdhuagdhc asuhduhuisnudh \n\nnew line \n\n\ntest paragraph\n`

**Comment by v-kydela** [comment]
@paigeflourin - Thank you for the post. May I ask for some clarification?

1. When you say "I am using web api to publish the qnamaker" do you mean you're using [this REST API](https://westus.dev.cognitive.microsoft.com/docs/services/5a93fcf85b4ccd136866eb37/operations/5ac266295b4ccd1554da75ff)?
2. What is your react app? Is it an app you made that calls the REST API?
3. When you say "this is the answer portion of my publish string that i am passong backend" do you mean it's an argument you're passing to the REST API?
4. When you say "however in qnamaker, the published answer became like this" do you mean that's what you see when you view the knowledge base in the QnAMaker portal (qnamaker.ai)?
5. Is the problem that the answer contains too many line breaks, or that the line breaks are escaped (i.e. they're showing up as `\n`)?

**Comment by paigeflourin** [comment]
> @paigeflourin - Thank you for the post. May I ask for some clarification?
> 
> 1. When you say "I am using web api to publish the qnamaker" do you mean you're using [this REST API](https://westus.dev.cognitive.microsoft.com/docs/services/5a93fcf85b4ccd136866eb37/operations/5ac266295b4ccd1554da75ff)?
> 2. What is your react app? Is it an app you made that calls the REST API?
> 3. When you say "this is the answer portion of my publish string that i am passong backend" do you mean it's an argument you're passing to the REST API?
> 4. When you say "however in qnamaker, the published answer became like this" do you mean that's what you see when you view the knowledge base in the QnAMaker portal (qnamaker.ai)?
> 5. Is the problem that the answer contains too many line breaks, or that the line breaks are escaped (i.e. they're showing up as `\n`)?

Hi @v-kydela , sorry i wasnt too clear
1) i am using an api service (web api hosted in azure) to publish the passed qna publish string to qnamaker
2) my react app is a sharepoint spfx application and yes i am calling my web api when passing the json string of the qnas
3) the answer portion yes, based from the publish string syntax from the qnamaker documentation,i have patterned the information based on the format that qnamaker needs. 
4) yes this is how i see in the test portion of the qnamaker. i pass <br> and i get \n\n in qnamaker
5) ys the problems is showing too many line breaks when i pass <br><br><br> i get \n\n and when i pass <br> i also get \n\n and when i preview it they all look the some, meaning no way to tell if it is a new line or a new paragraph

**Comment by v-kydela** [comment]
> i am using an api service (web api hosted in azure) to publish the passed qna publish string to qnamaker

Can you clarify this point a bit more? When you say "web api hosted in azure" do you mean one of these resources?
![image](https://user-images.githubusercontent.com/41968495/54224375-a127fd80-44b6-11e9-89a2-65a345ecb82f.png)

Do you mean a different kind of resource?

How does your web API work? Is your web API in turn calling [this REST API](https://westus.dev.cognitive.microsoft.com/docs/services/5a93fcf85b4ccd136866eb37/operations/5ac266295b4ccd1554da75ff)?

**Comment by v-kydela** [comment]
@paigeflourin - I am asking for clarification to help me try to reproduce the problem. But even without knowing more details, I can already suggest a solution. Have you tried replacing `<br>` with `\n` in the data you're passing to QnAMaker?

**Comment by v-kydela** [comment]
@paigeflourin - I just ran a test in the [API testing console](https://westus.dev.cognitive.microsoft.com/docs/services/5a93fcf85b4ccd136866eb37/operations/5ac266295b4ccd1554da75ff/console)

I supplied this as the body of my request:

```json
{
  "name": "QnA Maker FAQ",
  "qnaList": [
    {
      "id": 0,
      "answer": "0<br>0",
      "source": "Custom Editorial",
      "questions": [
        "Question 0"
      ],
      "metadata": []
    },
    {
      "id": 1,
      "answer": "1<br><br>1",
      "source": "Custom Editorial",
      "questions": [
        "Question 1"
      ],
      "metadata": []
    },
    {
      "id": 2,
      "answer": "2<br><br><br>2",
      "source": "Custom Editorial",
      "questions": [
        "Question 2"
      ],
      "metadata": []
    },
    {
      "id": 3,
      "answer": "3\n3",
      "source": "Custom Editorial",
      "questions": [
        "Question 3"
      ],
      "metadata": []
    },
    {
      "id": 4,
      "answer": "4\n\n4",
      "source": "Custom Editorial",
      "questions": [
        "Question 4"
      ],
      "metadata": []
    },
    {
      "id": 5,
      "answer": "5\n\n\n5",
      "source": "Custom Editorial",
      "questions": [
        "Question 5"
      ],
      "metadata": []
    }
  ],
  "urls": [
    "https://docs.microsoft.com/en-in/azure/cognitive-services/qnamaker/faqs",
    "https://docs.microsoft.com/en-us/bot-framework/resources-bot-framework-faq"
  ],
  "files": []
}
```

And it resulted in a knowledge base that looks like this:
![image](https://user-images.githubusercontent.com/41968495/54240188-9717f600-44da-11e9-8a81-0057e9b08553.png)

Here's what this means. `<br>`, `<br><br>`, and `<br><br><br>` all get converted into " \n\n". However, if you use `\n` to begin with instead of `<br>`, QnAMaker lets you include as many line breaks as you like.

Does this resolve your issue?

**Comment by paigeflourin** [comment]
> > i am using an api service (web api hosted in azure) to publish the passed qna publish string to qnamaker
> 
> Can you clarify this point a bit more? When you say "web api hosted in azure" do you mean one of these resources?
> ![image](https://user-images.githubusercontent.com/41968495/54224375-a127fd80-44b6-11e9-89a2-65a345ecb82f.png)
> 
> Do you mean a different kind of resource?
> 
> How does your web API work? Is your web API in turn calling [this REST API](https://westus.dev.cognitive.microsoft.com/docs/services/5a93fcf85b4ccd136866eb37/operations/5ac266295b4ccd1554da75ff)?

yes i hosted the api in azure, just liek that.

**Comment by paigeflourin** [comment]
> @paigeflourin - I just ran a test in the [API testing console](https://westus.dev.cognitive.microsoft.com/docs/services/5a93fcf85b4ccd136866eb37/operations/5ac266295b4ccd1554da75ff/console)
> 
> I supplied this as the body of my request:
> 
> ```json
> {
>   "name": "QnA Maker FAQ",
>   "qnaList": [
>     {
>       "id": 0,
>       "answer": "0<br>0",
>       "source": "Custom Editorial",
>       "questions": [
>         "Question 0"
>       ],
>       "metadata": []
>     },
>     {
>       "id": 1,
>       "answer": "1<br><br>1",
>       "source": "Custom Editorial",
>       "questions": [
>         "Question 1"
>       ],
>       "metadata": []
>     },
>     {
>       "id": 2,
>       "answer": "2<br><br><br>2",
>       "source": "Custom Editorial",
>       "questions": [
>         "Question 2"
>       ],
>       "metadata": []
>     },
>     {
>       "id": 3,
>       "answer": "3\n3",
>       "source": "Custom Editorial",
>       "questions": [
>         "Question 3"
>       ],
>       "metadata": []
>     },
>     {
>       "id": 4,
>       "answer": "4\n\n4",
>       "source": "Custom Editorial",
>       "questions": [
>         "Question 4"
>       ],
>       "metadata": []
>     },
>     {
>       "id": 5,
>       "answer": "5\n\n\n5",
>       "source": "Custom Editorial",
>       "questions": [
>         "Question 5"
>       ],
>       "metadata": []
>     }
>   ],
>   "urls": [
>     "https://docs.microsoft.com/en-in/azure/cognitive-services/qnamaker/faqs",
>     "https://docs.microsoft.com/en-us/bot-framework/resources-bot-framework-faq"
>   ],
>   "files": []
> }
> ```
> 
> And it resulted in a knowledge base that looks like this:
> ![image](https://user-images.githubusercontent.com/41968495/54240188-9717f600-44da-11e9-8a81-0057e9b08553.png)
> 
> Here's what this means. `<br>`, `<br><br>`, and `<br><br><br>` all get converted into " \n\n". However, if you use `\n` to begin with instead of `<br>`, QnAMaker lets you include as many line breaks as you like.
> 
> Does this resolve your issue?

how doe sit look like when  you test it out on the chatbot screen? i tried passing \n and it didn't make any difference on my end.

**Comment by v-kydela** [comment]
@paigeflourin - Okay, so your issue isn't about the way your answers are showing up in the QnAMaker portal but rather about how they're showing up in the chat window? This changes everything. Message formatting is channel-specific, and if a channel doesn't allow paragraph breaks then you'll need some kind of workaround. What channel are you using (Web Chat, Facebook Messenger, Slack, etc.)?

**Comment by paigeflourin** [comment]
> @paigeflourin - Okay, so your issue isn't about the way your answers are showing up in the QnAMaker portal but rather about how they're showing up in the chat window? This changes everything. Message formatting is channel-specific, and if a channel doesn't allow paragraph breaks then you'll need some kind of workaround. What channel are you using (Web Chat, Facebook Messenger, Slack, etc.)?

so i tried to publish this (passed from my react app):

>  {"add":{"qnaList":[{"id":0,"answer":"this is a new line\nnew line\n\n\nnew paragraph","source":"Editorial","questions":["test"],"metadata":[{"name":"classification","value":"Staff"},{"name":"SPID","value":108},{"name":"Division","value":"ADM"}]}]}}

got it in qnamaker as this:

![image](https://user-images.githubusercontent.com/6951524/54330957-c6517300-4652-11e9-9f6f-313ba0f0ec11.png)


then when i tested it out

![image](https://user-images.githubusercontent.com/6951524/54330992-f1d45d80-4652-11e9-8942-26d5ce1129c7.png)


it didnt actually catch the \n.

**Comment by v-kydela** [comment]
@paigeflourin - The test panel applies its own formatting. If you publish your QnAMaker app, you can test it with your own Postman or Curl commands and see that the API calls return the full answer text including the line breaks. Therefore it's up to whatever application that's displaying the answer to decide whether or not to display the line breaks.

Perhaps I've made a false assumption. Is this QnAMaker app meant to be used by a bot?

**Comment by paigeflourin** [comment]
> @paigeflourin - The test panel applies its own formatting. If you publish your QnAMaker app, you can test it with your own Postman or Curl commands and see that the API calls return the full answer text including the line breaks. Therefore it's up to whatever application that's displaying the answer to decide whether or not to display the line breaks.
> 
> Perhaps I've made a false assumption. Is this QnAMaker app meant to be used by a bot?

Hi! yes, it is meant to be used by a bot. sorry for the late reply.

**Comment by v-kydela** [comment]
Hi @paigeflourin 

What channel is your bot targeting?

**Comment by paigeflourin** [comment]
> Hi @paigeflourin
> 
> What channel is your bot targeting?

hmm sorry i am not also sure as there are others who is tasked to do the chatbot.


But i tried to replace <br> and pass \n 

![image](https://user-images.githubusercontent.com/6951524/54589243-16b83e80-4a60-11e9-8b04-d361d90b6073.png)


but tried it in Test, looked like it didnt recognize the \n

![image](https://user-images.githubusercontent.com/6951524/54589204-fd16f700-4a5f-11e9-83a5-43225f372843.png)

**Comment by v-kydela** [comment]
@paigeflourin - It's actually vitally important for you to know what channel your bot is targeting. The formatting that's applied to the answer is controlled entirely by the channel. As I've been saying, the way the answer looks in the testing panel is irrelevant. [This document](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-channels?view=azure-bot-service-4.0) might help you understand bot channels better.

A Teams bot is going to format its answers differently from a Facebook bot. And if you get the formatting to look correct in the testing panel, it might look wrong in the channel. That's why you need to know what channel you're using so you can go by the formatting of that channel and ignore the testing panel.

**Comment by paigeflourin** [comment]
hi @v-kydela ,

ive checked the azure portal and these are the channels used in the BOT.

![image](https://user-images.githubusercontent.com/6951524/54660886-1dec5480-4b13-11e9-8e4f-98598ce78087.png)

**Comment by v-kydela** [comment]
@paigeflourin - It looks like you have a Teams bot. Teams does indeed handle line breaks strangely. By default, Teams formats its messages using Markdown. In this current version of Teams, you can format each line break as two newline characters (\n or character ten) in order for Teams to render them. So an example string would be:

    Line\n\nbreak

Alternatively, you could use one of these:

    Line   \nbreak
    Line<br>break

Teams will eliminate blank lines, so \n\n\n\n\n doesn't do any more than \n\n. If you want to include a blank line as a paragraph break perhaps, you will need to put a non-breaking space character (&nbsp; or character 160) on that line. Here are some examples of how to write that in C#:

```c#
message = "Paragraph\n\n&nbsp;\n\nbreak";
message = "Paragraph\n\n\u00A0\n\nbreak";
message = "Paragraph\n\n\xA0\n\nbreak";
message = "Paragraph\n\n \n\nbreak"; // <-- That looks like a regular space but it's not
```

Alternatively, you can use HTML:

    Paragraph<br><br>break

The testing panel uses a sort of Markdown as well but it's more limited. Most of those options won't show up in the testing panel the way you want them to, and the testing panel doesn't render HTML. `&nbsp;` works though.

**Comment by v-kydela** [comment]
@paigeflourin - Are you still working on this?

**Comment by paigeflourin** [comment]
> @paigeflourin - Are you still working on this?

Hello, yes i am. but we can close this now. i have gained enough information thanks to you!
