### ISSUE TITLE
Missing Blob?

### ISSUE THREAD

**Issue by glasody** [Microsoft/BotBuilder-CognitiveServices#165]
Hi,
We have recently noticed that the QnA Maker is sometimes trying to query a blob called `qnamakerstore` and returns 404.
The exact address is `https://qnamakerstore.blob.core.windows.net/qnamakerdata/rankers/ranker-EnglishV2.ini`
This is causing queries to the qnamaker to fail sometimes.
It isnt a blob that exists in our azure subscription and it seems to be a generic store that is meant to be exist with the qnamaker
Please help.

Thank you

**Comment by v-kydela** [comment]
Hi @glasody 

Can you explain what you mean when you say you noticed QnA Maker is sometimes trying to query that blob? How did you notice it? What is trying to access that blob, and in what situations?

**Comment by glasody** [comment]
Hi @v-kydela,
We recently noticed this when doing cold starts in the morning alot.
If I look at the transaction details in AppInsights its like the following:
- [Request] POST /qnamaker/knowledgebases/{kbid}/generateanswer
- [Trace] RuntimeService Initialization
- [Dependency] POST /runtimecallback/config
- [Trace] 
```
RuntimeCallback returned config for Hostname:{hostname} values RankerVersion:V1, CallbackTimeoutInMinutes:30, CallbackUrl:https://qnamaker-service.trafficmanager.net/runtimecallback/config, ActiveLearning:{
  "enable": true,
  "clusteringIntervalInMinutes": 30,
  "clusteringHighSimilarityScore": 0.75,
  "clusteringVeryHighSimilarityScore": 0.9,
  "clusteringUserSuggestedCountMultiplier": 2,
  "maxNumberOfCluster": 100,
  "maxNumberOfQueriesInCluster": 10,
  "minimumScoreForLowScoreVariation": 20.0,
  "maximumScoreForLowScoreVariation": 95.0,
  "previousLowScoreVariationMultiplier": 0.8,
  "maxLowScoreVariationMultiplier": 1.6,
  "maxScoreForSingleAnswerSuggestion": 0.0
}, EM: True, TC: True, MI: False
```
- [Dependency] GET qnamakerstore 
  Command = https://qnamakerstore.blob.core.windows.net/qnamakerdata/Data_V1.zip
- [Dependency] GET qnamakerstore 
  Command = https://qnamakerstore.blob.core.windows.net/qnamakerdata/rankers/ranker-English.ini
- [Dependency] GET qnamakerstore 
  Command = https://qnamakerstore.blob.core.windows.net/qnamakerdata/rankers/ranker-EnglishV1.ini

Then i get a failed dependency call to 
https://qnamakerstore.blob.core.windows.net/qnamakerdata/rankers/ranker-EnglishV2.ini
which retries about 16 times then does a GET call to /synonymmaps

I'm' not sure why this is happening and Im not sure what I can do to make it go away.

Please let me know if there is any more detail I can provide.

Thank you.

**Comment by v-kydela** [comment]
@glasody - I've just observed 404 responses from ranker-EnglishV2.ini in my own logs. I've contacted the QnAMaker team and will let you know when I hear back.

**Comment by v-kydela** [comment]
@glasody - I've received a reply from the QnAMaker team:

> This is by design. The code , while loading the ranker, the code checks for a higher version, and loads if it exists. Current version in use is https://qnamakerstore.blob.core.windows.net/qnamakerdata/rankers/ranker-EnglishV1.ini , so it also checks for ranker-EnglishV2.ini. This is done for seamless rollout of new version if needed.
>
> This call is made only when the service is started or a KB is created. It’s not a periodic call.

I am considering this issue resolved. Feel free to ask more questions if you need any more help.
