### ISSUE TITLE
Facing issues in loading and publishing QnA maker knowledge base

### ISSUE THREAD

**Issue by maqankitat** [Microsoft/BotBuilder-CognitiveServices#167]
We need help in resolving following issues:

We faced below errors when we tried to publish QnA maker:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/44663443/55214978-3ef12b80-521e-11e9-9171-bb475d51a891.png)

![image](https://user-images.githubusercontent.com/44663443/55214992-4a445700-521e-11e9-958b-55562a5b3c95.png)

Following error is thrown we we tryto load KB: 

![image](https://user-images.githubusercontent.com/44663443/55215004-516b6500-521e-11e9-8f22-cbd66f90cad0.png)

We tried following things:
1. Restart App
2. Delete unused KB
3. VErified that there are no unsupported characters entered in QnA

**Comment by stevkan** [comment]
Are you still experiencing issues with publishing to QnA Maker? If so, can you list what steps you took that led to the issue? Can you also export and post a copy of the KB so I can investigate closer?

**Comment by maqankitat** [comment]
We have now deleted the QnA service and created a new Service hence can't export.. 
We had just tried publishing KB.
But every time we tried publishing the QnA it was showing one of the above errors

**Comment by stevkan** [comment]
After deleting and rebuilding, are you still having trouble or has it been resolved now?

**Comment by stevkan** [comment]
Closing as resolved.
