### ISSUE TITLE
Translator Services not working from Spanish to English?

### ISSUE THREAD

**Issue by Rykimaruh** [Microsoft/BotBuilder-CognitiveServices#168]
So I have a qna chatbot that is reading from a Spanish KB. I decided to add English translation using the Azure Translator Service. What I did notice was that the words translated from Spanish to English are really bad. Something like:

"Ver mas" should be translated to "See more", but instead it translates to "See but". 

I tested this translation out in Bing translator and it does translate to "See but", however I noticed that it was detecting Portuguese instead of Spanish.

I changed the detected language to Spanish and it was able to successfully translate to: "See more".

When I debugged in the code, I noticed that everything checks out fine. Meaning that it detected the Spanish or English language codes 'en' & 'es'. 

I honestly do not know what's going on, if it's something to do with the Translator Service not "trained"enough to detect and translate or what.

Any help is appreciated!

**Comment by CoHealer** [comment]
@Rykimaruh, this issue is not specific to the botframework but rather Microsoft Cognitive Services. You should open a new support request in Azure for Translator Services:

https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/newsupportrequest
