### ISSUE TITLE
Usages of IDialogContext are not async

### ISSUE THREAD

**Issue by onovotny** [microsoft/BotBuilder-CognitiveServices#17]
There are several places that call `IDialogContext.Wait(...)` in an async Task method. Those will block incorrectly. Please fix this to either remove the async and indicate it's a blocking method or actually make the code async.

https://github.com/Microsoft/BotBuilder-CognitiveServices/search?q=IDialogContext+&type=Code&utf8=%E2%9C%93

/cc @bdoodnauthBlueMetal

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
