### ISSUE TITLE
QnA Maker strict filtering in generate answer is no longer working

### ISSUE THREAD

**Issue by rosskyl** [Microsoft/BotBuilder-CognitiveServices#170]
Strict filtering was working in the past but is no longer working today. I am making the below request.

```
POST https://{name}.azurewebsites.net/qnamaker/knowledgebases/{knowledge-base-id}/generateAnswer
HEADERS:
Authorization: EndpointKey {endpoint-key}
Content-Type: application/json
BODY:
{
    "question": "What is this website",
    "top": 5,
    "strictFilters": [
        {
            "name": "relationshiptype",
            "value": "b2b"
        }
    ]
}
```

We can work around this by using 2 different knowledge bases, however this should be fixed.

**Comment by rosskyl** [comment]
Deleting everything related to QnA Maker and recreating and deploying fixed it.

**Comment by Zerryth** [comment]
Hmm interesting. Glad you're passed the issue. This comes up again, ping this thread again
