### ISSUE TITLE
QnAMaker returns "Runtime core is not initialized."

### ISSUE THREAD

**Issue by DrWala** [microsoft/BotBuilder-CognitiveServices#173]
Hi,

For some reason QnA Maker returns "Runtime core is not initialized." when I query it. Accessing the instance on qnamaker.ai returns "Please verify azure search service is up, restart the WebApp and try again".

The web app is up and azure search is running.

![image](https://user-images.githubusercontent.com/6803997/57459277-80590a00-72a5-11e9-9772-b8a8ef493658.png)

I can provide the kb id if needed.

I'm not sure if this is the right place but any assistance would be appreciated, as this was a client's bot that went down. If its the wrong place, please let me know where to post it.

**Comment by Zerryth** [comment]
@DrWala I'm unsure of what that error means myself, however I have reached out to the core QnA Team who builds the service, and asked for their advice. I'll keep you posted on any updates/if more info is needed

**Comment by Zerryth** [comment]
Actually @DrWala I just realized you can reach out to them more directly if you go to **qnamaker.ai** > **Feedback**
![image](https://user-images.githubusercontent.com/35248895/57536421-03578000-72f9-11e9-9917-0ad66d0b5070.png)

Then put your question through to there, and it'll create a ticket via UserVoice to the QnA team, where you can share your KB ID privately and other info if needed

Closing the issue here

**Comment by DrWala** [comment]
Hi, I actually found that after posting here and they got back to me with a solution. I'm not sure if I can post the fix here as it seems like an internal bug, I'll get permission and if so will drop it here as it might help others. Googling this literally turned up no results which is why I posted here in the first place haha

**Comment by Zerryth** [comment]
Sweet. Thanks for helping the community in advanced!

And if anything, hopefully next time someone needs help with QnAMaker specifically, they'll at least see that they can drop a ticket via their dashboard at qnamaker.ai :)

**Comment by DrWala** [comment]
Yep exactly - don't need people feeling like this guy: https://xkcd.com/979/

**Comment by DigitalSa1nt** [comment]
For anyone else coming across this, it's cause is usually down to the App Service Plan storage not being enough for the QnA App Service to download the required DLLs needed to function properly in this case the Runtime core dll. 

You can confirm this by opening up your App Service Plan in Azure and navigating to 'File System Storage' section which will show you available space.

The current fix for this is to upgrade to a service plan with more disk storage that's shared across all the deployed apps associated to that App Service Plan. Or alternatively you can ensure that your QnA services are all under their own individual app service plans; whatever fits your business processes best.
