### ISSUE TITLE
[QnA maker]QnAMaker confidence scores going down 

### ISSUE THREAD

**Issue by sanjeevgaut** [microsoft/BotBuilder-CognitiveServices#176]
Hi 

When i check a question in QNA maker, i get very good score and correct response. when i check same question through my code i get very low score. 
for example in qna maker i get score as 89 but in my code it get as low as 19 to 20.
I know scores can very from qna but this is huge difference

This is very strange behavior.
Qna KB ID: 2e7c7108-6dfb-4711-8296-743263c96dbe

@Microsoft Bot Framework

**Comment by CoHealer** [comment]
@jwiley84 , are you saying this is a duplicate issue?

**Comment by jwiley84** [comment]
Hi @sanjeevgaut! That is a very large gap. There should be a neglible difference between a test and published version, due to azure search indexing, but that's an 70%+ difference. 

Are you still having this issue?

**Comment by CoHealer** [comment]
Closing due to lack of response. @sanjeevgaut if you still require assistance please comment and re-open.
