### ISSUE TITLE
QnA maker API returns different confidence score

### ISSUE THREAD

**Issue by CalvinFengDatacom** [microsoft/BotBuilder-CognitiveServices#178]
Hi There,

We are facing an issue of getting different confidence scores when assigning true and false to property "isTest".  I remember few months earlier, we realised this issue when GA released, and now seems this issue is back again.

Can someone take a look? [Urgent]

KB Id: 6e7109f9-5696-4691-ab16-06bfb11d03d0

Thanks

**Comment by v-kydela** [comment]
Hello @CalvinFengDatacom 

I would like to help. Can you please provide repro steps and screenshots? Thank you.

**Comment by CalvinFengDatacom** [comment]
Thanks @v-kydela 

Here are the steps of what I have done in KB: 6e7109f9-5696-4691-ab16-06bfb11d03d0

1. Manually input few Questions & Answers, and Metadata.
2. Tested it in QnA maker portal, as for a specific question, I got **73.34** on Confidence Score.
3. But we couldn't get the answer from our Chat bot.
4. So I set up Postman to point to the same KB, and I realised the Confidence Score from Postman was **54.91**. The reason we couldn't get the answer from Chat bot is because we set the Threshold to 70, which means all answers' confidence score below 70 will be filtered out. 
5. And once I set "isTest":true in Postman request body, it returned the same answer as QnA maker portal and with the same Confidence Score, **73.34**

Test result in Postman: "isTest": false
![image](https://user-images.githubusercontent.com/26469662/61330729-5eb36a80-a874-11e9-9d7a-4c150e8ea7d2.png)

Test result in Postman: "isTest": true
![image](https://user-images.githubusercontent.com/26469662/61330713-52c7a880-a874-11e9-8ead-57212ee3a331.png)

**Comment by v-kydela** [comment]
@CalvinFengDatacom - Thank you for the info. Is it possible that you've made changes to your KB since the last time you published? Here are a few things to try:

1. Try publishing again and see if you get better results
2. Try increasing the value of `top` and see if you get better results

**Comment by CalvinFengDatacom** [comment]
@v-kydela Thanks for your comments. I have Trained the KB again, and re-published. Also increased the "top" value to 10. But, seems nothing has been changed.

**Comment by v-kydela** [comment]
@CalvinFengDatacom - I'm waiting on some feedback from the QnA support team and I will get back to you

**Comment by CalvinFengDatacom** [comment]
@v-kydela  Cool, thank you so much.

**Comment by v-kydela** [comment]
@CalvinFengDatacom - There's some good documentation [here](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/concepts/confidence-score#confidence-score-differences) that might help you understand the problem.

> The confidence score of an answer may change negligibly between the test and published version of the knowledge base even if the content is the same. This is because the content of the test and the published knowledge base are located in different Azure Search indexes. When you publish a knowledge base, the question and answer contents of your knowledge base moves from the test index to a production index in Azure search. See how the [publish](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/quickstarts/create-publish-knowledge-base#publish-the-knowledge-base) operation works.
>
> If you have a knowledge base in different regions, each region uses its own Azure Search index. Because different indexes are used, the scores will not be exactly the same.

**Comment by CalvinFengDatacom** [comment]
Thanks @v-kydela , I have confirmed we accidentally created a QnA Maker in West US, but we are using the Azure Search service in Australia East. And from my test, I can prove that you are right, once I created a new pair of QnA Maker and Azure Search both in Australia East, it gives me the same confidence scores in both test and publish environment. 
Thank you again for helping me work it out. 
I will close this issue :-)

**Comment by CalvinFengDatacom** [comment]
Hi, @v-kydela, since the last time we recreated the QnA maker service and Azure search at the same location, West US. We thought we have resolved this issue, however, the issue comes back again... 
Can you provide us any advise what should we do?
We also realised that we got different result and confidence score when every time we do a retain. The retain for us means the following steps:
1. exporting the existing KB to the *.tsv file
2. importing the *.tsv file
3. train the KB
4. publish the KB
So, why do we have different CS when every time we do the retain?

**Comment by CoHealer** [comment]
Reopening for @v-kydela to resume investigation.

**Comment by v-kydela** [comment]
@CalvinFengDatacom 

It sounds like you're having two issues:

1. You're saying your original issue has returned, where you get different scores depending on whether `isTest` is true or not
2. You're saying your scores change when you export and reimport your knowledge base

Is my understanding of your two issues correct?

I am unable to reproduce your first issue. When you say your "QnA maker service" is in the same location as your Azure Search service, do you mean your QnA Maker Cognitive Services resource or your QnA Maker app service resource? You might want to check both of those.

I am able to reproduce your second issue and I believe it indicates a QnA Maker bug. What I'm observing is that when I follow your export/reimport steps and resubmit my HTTP request to the `generateAnswer` endpoint, the answer's `id` field keeps getting higher and higher as though the imported KB still remembers the ID numbers from the overwritten KB and counts up from there instead of starting at 1. I also observe that the scores change, though they do stabilize after I repeat the process a few times. Please try repeating the process about 10 times and tell me if the scores ever stabilize or if you still get different scores every time. I will report the bug internally and I want to gather as much information as possible.

**Comment by CalvinFengDatacom** [comment]
@v-kydela 

Yes, these two issues are exactly what we have at the moment.

1. I have checked all the services that related to QnA maker and they all in the same location as listed below:
**Service name:                                   Location**
QnA Maker Cognitive Service:          West US
QnA App Service Plan:                      West US
QnA App Service:                              West US
QnA App Insights:                             West US
Azure Search Service:                        West US

2. I have tried to repeat the process more than 10 times and I can see the confident scores are still unstable every time. 

Can you please raise this bug with MS?
Another question is, will it be better if I'm using the API to upload the content rather than using the QnA KB portal?

**Comment by v-kydela** [comment]
@CalvinFengDatacom - There shouldn't be any difference in your KB if you use the authoring API rather than the portal

**Comment by v-kydela** [comment]
@CalvinFengDatacom - Since I'm not able to reproduce the behavior you're experiencing, I think it would be best if you go ahead and report this yourself. In https://www.qnamaker.ai/ use Feedback > Send us a Message.
