### ISSUE TITLE
[Node.js] Add typings 

### ISSUE THREAD

**Issue by palmerabollo** [microsoft/BotBuilder-CognitiveServices#26]
[`typings` in the package.json](https://github.com/Microsoft/BotBuilder-CognitiveServices/blob/master/Node/package.json#L5) points to an unexisting typescript definitions file:

```
"typings": "./lib/botbuilder-cognitiveservices.d.ts"
```

This file should be included in the published npm module, so we can use typescript definitions without pain.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
