### ISSUE TITLE
[Node.js] Follow semantic versioning (suggestion)

### ISSUE THREAD

**Issue by palmerabollo** [Microsoft/BotBuilder-CognitiveServices#27]
In the Node.js community it's a good practice to adhere to the [semantic versioning](http://semver.org/) to avoid compatibility issues.

For example, the latest botbuilder-cognitiveservices@1.1.0 broke backwards compatibility. It should have been 2.0.0. Otherwise some bots using ^1.0.0 in their package.json files would fail.

**Comment by greuze** [comment]
Happened the same to me

**Comment by dasvictor** [comment]
Sorry for the inconvenience. We'll take care of this going forward.
