### ISSUE TITLE
Update to latest BotBuilder version

### ISSUE THREAD

**Issue by ejadib** [Microsoft/BotBuilder-CognitiveServices#28]
Due to the latest updates of the BotBuilder C#, QnAMaker is failing with a missing exception:

Method not found: 'Void Microsoft.Bot.Builder.Dialogs.PromptDialog.Confirm(Microsoft.Bot.Builder.Dialogs.IDialogContext, Microsoft.Bot.Builder.Dialogs.ResumeAfter`1, System.String, System.String, Int32, Microsoft.Bot.Builder.Dialogs.PromptStyle)

This is exactly the same issue that happened on [BotBuilder-Location](https://github.com/Microsoft/BotBuilder-Location/) as described [here](https://github.com/Microsoft/BotBuilder-Location/issues/107).

**Comment by rohantare** [comment]
Hello,

I am using Visual studio 2017 with Bot framework 3.8.1. Created simple QnA Maker dialog using with cognitive services 1.1.0.
QnA maker is working fine, I have tested it online. However when I test the bot which triggers QnA maker I get following exception :

Exception: Method not found: 'Void Microsoft.Bot.Builder.Dialogs.PromptOptions1..ctor(System.String, System.String, System.String, System.Collections.Generic.IReadOnlyList1<!0>, Int32, Microsoft.Bot.Builder.Dialogs.PromptStyler, System.Collections.Generic.IReadOnlyList`1<System.String>)'.",

This works well when I develop using Visual Studio 2015.

What could be the issue?

**Comment by ejadib** [comment]
As I explained in [StackOverflow](https://stackoverflow.com/questions/44315999/bot-framework-qna-maker-method-not-found-exception/44316266#44316266), the issue is due to the latest update on BotBuilder. The QnA Maker library needs to be updated to the latest version of BotBuilder; you can do it yourself as it's likely it will be just recompiling the library without many breaking changes.

**Comment by SUGPZ** [comment]
I update Microsoft.Bot.Builder to 3.8.3 but still I get this exception for some questions. (Questions having any word duplicated in multiple questions)

**Comment by SUGPZ** [comment]
I got it, it is because I use some parameteres to [QnAMakerQnAMaker("Subscription key", "Kbid", "I'm sorry, I didn’t get that. "**,0.50,3**] By replacing it with [QnAMakerQnAMaker("Subscription key", "Kbid", "I'm sorry, I didn’t get that. "] Solves my issue.

**Comment by NioZero** [comment]
Hi, while we wait for this bug to be resolved, is there another way to return more than one answer?

**Comment by ejadib** [comment]
Closing this as it was already addressed in #40 and #41
