### ISSUE TITLE
QnAMakerDialog isn't a type

### ISSUE THREAD

**Issue by Nostreum** [Microsoft/BotBuilder-CognitiveServices#29]
Hi ! 

When i try to compile the SimpleQnABot, i get an issue here : 
          public class SimpleQnADialog : QnAMakerDialog (<---)
QnAMakerDialog is a namespace and not a type. I tried QnAMakerDialog\<object\> or other stuffs but i get different problems.

**Comment by SUGPZ** [comment]
I had the same problem. It may be because of conflict in dll. Did you install QnaMaker or QnAMakerDialog from nuget packages? If yes uninstall these packages. You need only Microsoft.Bot.Builder.CognitiveServices for QnAMaker Bot.

**Comment by dasvictor** [comment]
The samples provided are for the package Microsoft.Bot.Builder.CognitiveServices.
Feel free to reopen the issue, if it doesn't work with the above mentioned package.
