### ISSUE TITLE
How to access default message from QnaMaker?

### ISSUE THREAD

**Issue by SUGPZ** [microsoft/BotBuilder-CognitiveServices#31]
I have     [QnAMaker("Subscription key", "Kbit key", "I'm sorry, I didn’t get that", 0.50, 3)]
I want this default message, i.e. "I'm sorry, I didn’t get that" , to provide more information how could I do that? How can I access It?

**Comment by ronnelsantiago** [comment]
What sort of more information you want to get from it?

**Comment by SUGPZ** [comment]
Using that message I want to send more messages to user.

**Comment by dasvictor** [comment]
As far as the message is a string, it should just work. Can you please elaborate on what issue you are facing?

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
