### ISSUE TITLE
Qna maker dialog is not found whenever it is called from the another file

### ISSUE THREAD

**Issue by sjais789** [microsoft/BotBuilder-CognitiveServices#37]
whenever i try to call a dialog except from here( bot.dialog('/',Qnamaker).
QnaMaker dialog failed to be load.

**Comment by ronnelsantiago** [comment]
what sort of error message you are getting?

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
