### ISSUE TITLE
Mismatch in QnaMakerDialog return type?

### ISSUE THREAD

**Issue by tiloc** [microsoft/BotBuilder-CognitiveServices#39]
Hi,
in the C# QnaMakerDialog, the dialog class is defined as 
QnAMakerDialog : IDialog<**IMessageActivity**>

But it invokes "context.Done(**true**)". In my bot I am getting exceptions about mis-matches between IMessageActivity and Boolean, when I am awaiting the results from the dialog.

I have the impression that these two types need to be aligned?

**Comment by arijitdas** [comment]
Running into the same issue while trying the approach Gary suggested [here](http://www.garypretty.co.uk/2017/03/26/forwarding-activities-messages-to-other-dialogs-in-microsoft-bot-framework/).

**Comment by tiloc** [comment]
FWIW: PR #46 which fixes this behavior is now meeting the CLA requirement and could be pulled.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
