### ISSUE TITLE
Is there an API for getting a list of QnAMaker services for a subscription?

### ISSUE THREAD

**Issue by pkpaul5** [microsoft/BotBuilder-CognitiveServices#42]
I checked in the list of QnAMaker APIs(https://westus.dev.cognitive.microsoft.com/docs/services/58994a073d9e04097c7ba6fe/operations/58994a073d9e041ad42d9baa).

There is no API for getting list of QnAMaker services.

**Comment by dasvictor** [comment]
There is no API to get the list of services atm.

**Comment by In8Beats** [comment]
Can we get this please? It seems kind of crazy you can create and publish, but not list. How can we develop simple update strategies for knowledge bases if we can't list them?

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
