### ISSUE TITLE
QnA Maker  Train API is not working?

### ISSUE THREAD

**Issue by pkpaul5** [microsoft/BotBuilder-CognitiveServices#43]
I am trying to train Microsoft QnAMaker programmatically for alternate question. I am calling the REST API for training for more than 50 times for alternate question. But it is not working. The code is provided below :

var client = new HttpClient();
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            client.DefaultRequestHeaders.Add("Ocp-Apim-Subscription-Key", "b6da7e5e904148a88e651d3781e3e519");
            var uri = "https://westus.api.cognitive.microsoft.com/qnamaker/v2.0/knowledgebases/e31c0d13-6531-4af6-9352-5f7c125d448d/train";

            HttpResponseMessage response;
            QnAMakerTrainObject data = new QnAMakerTrainObject();
            data.feedbackRecords = new List<FeedbackRecord>();
            FeedbackRecord f = new FeedbackRecord();
            f.kbQuestion = "q3";
            f.kbAnswer = "a3";
            f.userQuestion = question;
            f.userId = userID;
            data.feedbackRecords.Add(f);
            string json = JsonConvert.SerializeObject(data);
            byte[] messageBytes = System.Text.Encoding.UTF8.GetBytes(json);

            var content = new ByteArrayContent(messageBytes);
            content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/json");
            var method = new HttpMethod("PATCH");
            var request = new HttpRequestMessage(method, uri);
            request.Content = content;
            response = await client.SendAsync(request);

            if (response.IsSuccessStatusCode)
            {
                var responseContent = response.Content;
                string responseString = responseContent.ReadAsStringAsync().Result;
            }

**Comment by dasvictor** [comment]
You can take a look at https://qnamaker.ai/Documentation/ActiveLearning.
The learning gets triggered for every 50 entries, but the system may not be confident enough to make any updates.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
