### ISSUE TITLE
Active Leaning for QnA Maker 

### ISSUE THREAD

**Issue by anirudhaditya** [microsoft/BotBuilder-CognitiveServices#44]
We are in the process of enabling Active Learning (https://qnamaker.ai/Documentation/ActiveLearning). As QnA maker is primarily a key word matching solution only as of date, we are making an attempt to provide active learning process which will allow users to have multiple options.

One issue is that the default configuration of Active learning is **50 user clicks** and I was trying to figure out if we can reduce that to 5 or 6. Have anyone tried this before or can provide me some suggestions.

Thanks
Aniruddha

**Comment by dasvictor** [comment]
We are looking towards making it configurable in future. As a work-around for now, you can try updating the feebackRecords array with same entries but different user Ids.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
