### ISSUE TITLE
QnaMaker dialog cannot open with a prompt

### ISSUE THREAD

**Issue by tiloc** [microsoft/BotBuilder-CognitiveServices#48]
For user guidance I find it beneficial to let the user know what kind of input is expected of them. In the case of the Q&A dialog, this might be a cue such as "Ask me anything about cooking veggies!". 

With the current  design of the QnaMaker dialog I found it challenging to easily do so (StartAsync cannot be overridden) and had resorted to letting the dialog which invokes the QnaMaker dialog  output a prompt prior to calling the QnaMaker dialog. I think from a design perspective, the QnaMaker dialog should be self-contained and be able to emit its own prompt.

I have filed this issue as a motivation for the PR which I am about to submit. The PR adds a "Prompt" property to the QnaMaker dialog which can be used for the described purpose. The use of the Prompt is optional, no breaking change. I have modeled this after the Prompt property in the ContosoFlowerBot PagedCarouselDialog.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
