### ISSUE TITLE
QnAMakerScorable: PrepareAsync will always return a response

### ISSUE THREAD

**Issue by ejadib** [microsoft/BotBuilder-CognitiveServices#5]
With the current implementation, there is almost no chance for the [`QnAMakerScorable `](https://github.com/Microsoft/BotBuilder-CognitiveServices/blob/master/CSharp/Library/QnAMaker/QnAMakerScorable.cs)to return `false` in the [`PrepareAsync `](https://github.com/Microsoft/BotBuilder-CognitiveServices/blob/master/CSharp/Library/QnAMaker/QnAMakerScorable.cs#L64) method.

Since the [`QnAMakerService`](https://github.com/Microsoft/BotBuilder-CognitiveServices/blob/master/CSharp/Library/QnAMaker/QnAMakerService/QnAMakerService.cs) [will always return a `QnAMakerResult `with a score of 0](https://github.com/Microsoft/BotBuilder-CognitiveServices/blob/master/CSharp/Library/QnAMaker/QnAMakerService/QnAMakerService.cs#L117) when the answer from the QnA service has a lower score than the threshold and because the answer of that `QnAMakerResult` will be the default message that cannot be null or empty either as in the [`QnAMakerAttribute`](https://github.com/Microsoft/BotBuilder-CognitiveServices/blob/master/CSharp/Library/QnAMaker/QnAMakerService/QnAMakerAttribute.cs) is [being replaced with the default message](https://github.com/Microsoft/BotBuilder-CognitiveServices/blob/master/CSharp/Library/QnAMaker/QnAMakerService/QnAMakerAttribute.cs#L76) from the resource file, [this logic](https://github.com/Microsoft/BotBuilder-CognitiveServices/blob/master/CSharp/Library/QnAMaker/QnAMakerScorable.cs#L71) in the `QnAMakerScorable` makes the method to always return a response.

We are looking to use the Scorable as part of a bigger solution and we want to allow to continue the execution through other dialogs when the threshold is not met. 

A possible way to fix this could be allowing the default message to be null/emtpy and in the QnAMakerService return null when the default message is not provided instead of QnAMakerResult with a default message and an score of 0.

**Comment by willportnoy** [comment]
You might also consider splitting the scorables into two parts - one that produces a score of QnAMakerResult and one that projects that QnAMakerResult to a normalized 0 to 1 score.  It makes it easier to compose other parts like Where and WhereScore on top of your pieces.

See these for an example:

https://github.com/Microsoft/BotBuilder/blob/develop/CSharp/Library/Microsoft.Bot.Builder/Scorables/Actions.cs#L203

https://github.com/Microsoft/BotBuilder/blob/develop/CSharp/Library/Microsoft.Bot.Builder/Scorables/Actions.cs#L187

@msft-shahins do you think you'll release the latest bot builder soon with the scorable fixes?

**Comment by ejadib** [comment]
From what I'm seeing, the normalization is happening at the [QnAMakerService](https://github.com/Microsoft/BotBuilder-CognitiveServices/blob/master/CSharp/Library/QnAMaker/QnAMakerService/QnAMakerService.cs#L111). 

So, I'm understood OK what you are suggesting, the QnAMakerService will return the result as is ([this line](https://github.com/Microsoft/BotBuilder-CognitiveServices/blob/master/CSharp/Library/QnAMaker/QnAMakerService/QnAMakerService.cs#L110)), without doing any processing (meaning without checking the threshold and without returning an QnAMakerResult with the default answer) . Then we will have two scorables:

- one that just normalize the score returned by QnAMaker and use it; eg. to check agains the threshold and return true or false based on that.
- and the other one that does something custom, based on the QnAMaker score, to project a new score

Is that what you meant? I assume that for our solution we should use the first scorable in that case, right?

**Comment by willportnoy** [comment]
@ejadib yes, that decomposition is what I meant, so that you can have access to the full QnAMakerResult if you want.

But I agree, it would be better for the service not to manipulate the results in its implementation in favor of preserving as much information as possible.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
