### ISSUE TITLE
QnAMakerDialog: Provide ability to override behaviour for no match scenario

### ISSUE THREAD

**Issue by gliddell** [microsoft/BotBuilder-CognitiveServices#50]
I want my bot to be able to take a different course of action if the QnAMakerDialog does not find a matching answer. For example, not being able to find an answer might result in an automatic transfer of the chat to a human agent. I believe this to be a small change to QnAMakerDialog.js as follows. All I did was extracted the sending of the message in the no match case to its own method.

```javascript
QnAMakerDialog.prototype.invokeAnswer = function (session, recognizeResult, threshold, noMatchMessage) {
        var qnaMakerResult = recognizeResult;
        session.privateConversationData.qnaFeedbackUserQuestion = session.message.text;
        if (qnaMakerResult.score >= threshold && qnaMakerResult.answers.length > 0) {
            if (this.isConfidentAnswer(qnaMakerResult) || this.qnaMakerTools == null) {
                this.respondFromQnAMakerResult(session, qnaMakerResult);
                this.defaultWaitNextMessage(session, qnaMakerResult);
            }
            else {
                this.qnaFeedbackStep(session, qnaMakerResult);
            }
        }
        else {
                this.noMatch(session, noMatchMessage, qnaMakerResult);
        }
    };

QnAMakerDialog.prototype.noMatch = function (session, noMatchMessage, qnaMakerResult) {
            session.send(noMatchMessage);
            this.defaultWaitNextMessage(session, qnaMakerResult);
};
```

**Comment by dvm-2k1** [comment]
Hi All,

We too have similar requirement about "No match found" scenarios... it would be helpful if this can be included as a virtual/abstract method in QnAMakerDialog which gives flexibility for consuming bot service dialog to override this method with custom logic. Please let us know once this is included to get that new nuget packages...

Thanks, Venu Madhav Deevi.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
