### ISSUE TITLE
Is there API for editing utternace in LUIS?

### ISSUE THREAD

**Issue by pkpaul5** [microsoft/BotBuilder-CognitiveServices#55]
I did not find any API documentation(https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c08) for updating a LUIS utterance.
Please let me know if there is any API for updating LUIS utterance.

**Comment by stevengum97** [comment]
You can actually use that same API to update the LUIS utterance, as the utterance ID will remain the same. For example, changing the intent of an utterance using the API will return a response body which will show that the utterance ID is still the same.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
