### ISSUE TITLE
Use multiple QnA services in one bot

### ISSUE THREAD

**Issue by auanish** [microsoft/BotBuilder-CognitiveServices#56]
I have multiple QnA services running, each with it's own knowledgeBaseId and subscriptionKey. I want to use them both in a single chatbot and I've written a piece of code which takes the user input and assigns the correct Knowledgebase details. However, I'm unable to get the 2nd QnA service to become active and the bot is linking only to the first service. What might be going wrong here?

**Sample code:**
```
var knowledgeId = "FIRST_QNA_SERVICE_KNOWLEDGE_ID"; 
var subscriptionId = "FIRST_QNA_SERVICE_SUBSCRIPTION_ID";

var bot = new builder.UniversalBot(connector);

var qnarecognizer = new cognitiveservices.QnAMakerRecognizer({
    knowledgeBaseId: knowledgeId, 
    subscriptionKey: subscriptionId,
    qnaThreshold:0.3,
    top:1});

var intentrecognizer = new builder.IntentDialog();

var intents = new builder.IntentDialog({ recognizers: [intentrecognizer, qnarecognizer] });
bot.dialog('/', intents);

intents.matches('qna', [
    function (session, args, next) {
            args.entities.forEach(function(element) {
            session.send(element.entity);     
        }, this);           
    }
]);

intents.matchesAny([/hi/i, /main menu/i], [
    function (session) {
   builder.Prompts.choice(session, "Hi, What would you like to ask me about?", ["Service1","Service2"],{ listStyle: builder.ListStyle.button});

    },

       function (session, result) {
    var selection = result.response.entity;
           switch (selection) {
               case "Service1":
                    knowledgeId = "FIRST_QNA_SERVICE_KNOWLEDGE_ID"; 
                    subscriptionId = "FIRST_QNA_SERVICE_SUBSCRIPTION_ID";
                    session.send('You can now ask me anything about '+selection+'. Type \'main menu\' anytime to choose a different topic.')
                    session.endConversation();
                    return 

               case "Service2":
                    knowledgeId = "SECOND_QNA_SERVICE_KNOWLEDGE_ID"; 
                    subscriptionId = "SECOND_QNA_SERVICE_SUBSCRIPTION_ID";
                    session.send('You can now ask me anything about '+selection+'. Type \'main menu\' anytime to choose a different topic.')
                    session.endConversation();
                    return 

           }
   }

])
```

**Comment by filsdegandalf** [comment]
Hello @auanish 

the QnaMakerDialog is always getting the first element of the recognizers array to run.

`    function QnAMakerDialog(options) {
        var _this = _super.call(this) || this;
        _this.options = options;
        _this.recognizers = new builder.IntentRecognizerSet(options);
        var qnaRecognizer = _this.options.recognizers[0];
        _this.ocpApimSubscriptionKey = qnaRecognizer.ocpApimSubscriptionKey;
        _this.kbUriForTraining = qnaRecognizer.kbUriForTraining;
        _this.qnaMakerTools = _this.options.feedbackLib;
        if (typeof _this.options.qnaThreshold !== 'number') {
            _this.answerThreshold = 0.3;
        }
        else {
            _this.answerThreshold = _this.options.qnaThreshold;
        }
        if (_this.options.defaultMessage && _this.options.defaultMessage !== "") {
            _this.defaultNoMatchMessage = _this.options.defaultMessage;
        }
        else {
            _this.defaultNoMatchMessage = "No match found!";
        }
        return _this;
    }`

to avoid this you can create your owndialog with the proper config following each case 

`
if(a){
       let qnaMakerDialog: any = new QnAMakerDialog({
            recognizers: [this.recognizerA],
            defaultMessage: "No match! Try changing the query terms!",
            qnaThreshold: 0.3,
            feedbackLib: this.customQnAMakerTools
        });
} else {
       let qnaMakerDialog: any = new QnAMakerDialog({
            recognizers: [this.recognizerB],
            defaultMessage: "No match! Try changing the query terms!",
            qnaThreshold: 0.3,
            feedbackLib: this.customQnAMakerTools
        });
}
`

Regards,

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
