### ISSUE TITLE
"Exception: invalid type: expected Microsoft.Bot.Connector.IMessageActivity, have Boolean" when calling derive QnAMakerDialog using context.Call

### ISSUE THREAD

**Issue by gabog** [microsoft/BotBuilder-CognitiveServices#57]
When I call my derived QnADialog using context.Call(myDialog, MyCallBack) I get an "Exception: invalid type: expected Microsoft.Bot.Connector.IMessageActivity, have Boolean" exception.

Example:

        [LuisIntent("AskQuestion")]
        public async Task AskQuestion(IDialogContext context, LuisResult result)
        {
            var message = context.MakeMessage();
            message.Text = "In Q&A Dialog";
            message.Speak = "OK, ask me some questions and I'll do my best to respond.";
            message.InputHint = InputHints.ExpectingInput;
            await context.PostAsync(message);

            var dialog = new MyQnADialog(); ;
            context.Call(dialog, DialogDone);
        }

        private async Task DialogDone(IDialogContext context, IAwaitable<object> result)
        {
            await result;
            context.Done(0);
        }

I was able to workaround the issue but overriding DefaultWaitNextMessageAsync as follows in MyQnADialog:

        protected override async Task DefaultWaitNextMessageAsync(IDialogContext context, IMessageActivity message, QnAMakerResults result)
        {
            context.Done<IMessageActivity>(null);
        }

I think this is a bug and the default implementation for QnAMakerDialog.DefaultWaitNextMessageAsync should be similar to the code above instead of context.Done(true); like it is today.

**Comment by SlashNS** [comment]
agreed. i was running into the same issue. Thanks for the workaround!

**Comment by mlipinski** [comment]
I am having this exact same issue and could use some help getting around it.

Any help would be greatly appreciated.

**Comment by SlashNS** [comment]
the workaround from OP worked for me.

**Comment by houdinisparks** [comment]
thank you!

**Comment by Yudner** [comment]
It also works by removing the line: "context.Done<IMessageActivity>(null);"

* it would be like that.
protected override async Task DefaultWaitNextMessageAsync(IDialogContext context, IMessageActivity message, QnAMakerResults result)
    {
        
    }

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
