### ISSUE TITLE
sendDefaultMessageAndWait not flexible

### ISSUE THREAD

**Issue by MinaMoussa** [microsoft/BotBuilder-CognitiveServices#58]
Is it possible to change this method so user gets the option to NOT send a default reply if the confidence is low/answers =0. Sometimes it's good for bot to go silent when it doesnt know the answer and answer when it does know. This will make things allot easier:

Method to reply

if (sendDefaultMessageAndWait)
                    {
                        await context.PostAsync(qnaMakerResults.ServiceCfg.DefaultMessage);
                        await this.DefaultWaitNextMessageAsync(context, message, qnaMakerResults);
                    }

or atleast wrap this into a virtual method that can be overriden

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
