### ISSUE TITLE
Confusing handling of CLA agreement

### ISSUE THREAD

**Issue by tiloc** [microsoft/BotBuilder-CognitiveServices#59]
I have submitted two PRs, and they have been flagged with cla-notrequired (they are both very simplistic fixes and additions). I have rechecked about whether they have been pulled in the meanwhile, and have noticed that the cla-notrequired tag has been removed on one of them, and it is pending, awaiting the signing of the CLA? The contributing guideline is setting a limit of 15 lines of code, my PRs are well below that. What has happened?
I am referring to PR #39.

**Comment by stevengum97** [comment]
I'm not sure what the exact specifications are for the CLA as I'm not a legal specialist, but for PR #46, GitHub lists 7 additions and 9 deletions, which (perhaps rather simplistically) means 16 lines were modified. #39 is an issue, not a PR, and #46 addresses the issue.

I noticed that in the PR you moved around some namespaces at the beginning of your file. I think not moving those would put you back under the 15 line limit.

**Comment by tiloc** [comment]
Thank you for your take on this. I have modified my PR #46 to reduce the number of rearrangements and it is 12 changed lines now. Hope this helps in its acceptance.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
