### ISSUE TITLE
[QnA Maker] More than one response from HTTP request

### ISSUE THREAD

**Issue by nvoliver** [Microsoft/BotBuilder-CognitiveServices#6]
As far as I understand, an HTTP request with the 'generateanswer' appendix will always return the result with the highest score only.

What we would need is something like a "Top-5" results list, because several answers from the Knowledge Base may be relevant. In our case, it is up to the user to make a decision for the best match.

Is it possible to extend QnA Maker's API requests to something like this function?
 https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.entityrecognizer.html#findallmatches

**Comment by palmerabollo** [comment]
@nvoliver `QnAMakerRecognizer` seems to provide an array of answers now (I'm using botbuilder-cognitiveservices@1.1.0)

```json
{
  "action": "trigger(qna:qna)",
  "intent": {
    "answers": [
      {
        "answer": "Hello",
        "questions": [
          "hi"
        ],
        "score": 1
      }
    ],
    "score": 1,
    "entities": [
      {
        "score": 1,
        "entity": "Hello",
        "type": "answer"
      }
    ],
    "intent": "qna"
  },
  "libraryName": "qna"
}
```

**Comment by nvoliver** [comment]
This is great, thanks @palmerabollo!

**Comment by shikelong** [comment]
Any one know how to get "top-5" result when using C# sdk? Regards.

**Comment by shikelong** [comment]
I got it,  using the generateAnswer api
Pass top param into body, the default value is 1.
