### ISSUE TITLE
qnamakerTools ends dialog twice

### ISSUE THREAD

**Issue by ubreddy** [microsoft/BotBuilder-CognitiveServices#60]
In the answerSelection dialog the second function the endDialog is called twice once with Result and once more later... any reason why twice?
```
            function (session, results) {
                if (results && results.response && results.response.entity) {
                    var qnaMakerResult = session.dialogData.qnaMakerResult;
                    var filteredResult = qnaMakerResult.answers.filter(function (qna) { return qna.questions[0] === results.response.entity; });
                    if (filteredResult !== null && filteredResult.length > 0) {
                        var selectedQnA = filteredResult[0];
                        session.send(selectedQnA.answer);
                        session.endDialogWithResult(selectedQnA);
                    }
                }
                else {
                    session.send("Sorry! Not able to match any of the options.");
                }
                session.endDialog();
            },

```
This is causing parent dialogue calling qnamakerdialog behave erratically esp when overriding the defaultWaitNextMessage which is doing some beginDialog work...

Can we remove the second endDialog? which is anyway the last statement in the answerSelection dialog?

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
