### ISSUE TITLE
EDIT: duplicate

### ISSUE THREAD

**Issue by RaffaelHold** [microsoft/BotBuilder-CognitiveServices#61]
In the current version of the Microsoft.Bot.Builder.CognitiveServices (v1.1.1) package the QnAMakerDialog implements the IDialog<IMessageActivity> but does call context.Done() with a boolean argument instead of an IMessageActivity inside its DefaultWaitNextMessageAsync method. 

This causes the deserialization of the dialogs result to fail in the parent dialogs ResumeAfter implementation.

**Comment by RaffaelHold** [comment]
My bad. An existing issue already mentions this behaviour

**Comment by tiloc** [comment]
See PR #46 for resolution. Unfortunately not pulled in yet.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
