### ISSUE TITLE
QnAMakerRecognizer should implement BotBuilder's IntentRecognizer

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/BotBuilder-CognitiveServices#62]
It would be useful for the BotBuilder Node sdk if the QnAMakerRecognizer implemented BotBuilder's IntentRecognizer: https://github.com/Microsoft/BotBuilder/blob/070acb410b70312f418d23e032013c4ddf90fdc5/Node/core/lib/dialogs/IntentRecognizer.js  providing OnEnabled and OnFilter

This issue was raised on StackOverflow: https://stackoverflow.com/questions/46688548/using-onenabled-method-with-qnamakerrecognizer

**Comment by sajal2692** [comment]
Hey, any updates on this? It would be helpful to enable/disable QnA Maker as and when desired.

**Comment by dividor** [comment]
This would be very useful for us too: https://stackoverflow.com/questions/50901325/change-list-of-recognizers-depending-on-user

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
