### ISSUE TITLE
QnARecognizer.js results in Error when there is a backslash

### ISSUE THREAD

**Issue by stoconnor** [microsoft/BotBuilder-CognitiveServices#66]
When there is a backslash character (i.e \) in a message to the bot it results in the following error:

```
TypeError: Cannot read property 'length' of undefined
    at Request._callback (C:\Dev\MyBot\node_modules\botbuilder-cognitiveservices\lib\QnAMakerRecognizer.js:54:70)
    at Request.self.callback (C:\Dev\MyBot\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Dev\MyBot\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Dev\MyBot\node_modules\request\request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
/ - ERROR: Cannot read property 'length' of undefined
```

**Comment by stoconnor** [comment]
Line 54 needs to be changed from:
`if (result.answers !== null && result.answers.length > 0) {`

To:
`if (result.answers !== undefined && result.answers.length > 0) {`

**Comment by Kellym-Kainos** [comment]
This also happened to me when developing locally but I realised I hadn't got my env file configured properly. Ensure that you have properly set your KNOWLEDGE_BASE_ID and SUBSCRIPTION_KEY env variables correctly

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
