### ISSUE TITLE
QnARecognizer.js results throws error,while parsing response,  need code change.

### ISSUE THREAD

**Issue by masteroes** [microsoft/BotBuilder-CognitiveServices#70]
Getting error
TypeError: Cannot read property 'length' of undefined
    at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder-cognitiveservices\lib\QnAMakerRecognizer.js:54:70)
when we get response 
{ error: 
   { code: 'RateLimitExceeded',
     message: 'Rate limit is exceeded. Try again later.' } }

Code change requires at line 54:
From:
if (result.answers !== null && result.answers.length > 0) {
To:
if (result.answers && result.answers.length > 0) {

**Comment by Kellym-Kainos** [comment]
This also happened to me when developing locally but I realised I hadn't got my env file configured properly. Ensure that you have properly set your KNOWLEDGE_BASE_ID and SUBSCRIPTION_KEY env variables correctly

**Comment by tatsuya-takahashi** [comment]
This also happened to me
Only score is setted, but answers is not setted.

![issue](https://user-images.githubusercontent.com/34804215/36880653-37f750d4-1e0d-11e8-8233-72895776fa98.png)

**Comment by masteroes** [comment]
observed the updates /fixes are in git, but not yet published for npm

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
