### ISSUE TITLE
Feedback library incorrect answer if question doesn't matches list of options

### ISSUE THREAD

**Issue by rcha37** [microsoft/BotBuilder-CognitiveServices#71]
While using feedback library of QnAMaker, user is displayed options to choose result from. Now if user doesn't pick any option from the list displayed and sends different question to bot. Then QnAMaker is responding with one of the answers, which is matching from list of options or else no match found is returned. Even if question exist in qnamaker.ai. Please find example below :-

**Question:** Bot
**QnaMaker reply:**
What is a bot?
How do I stop bot?
What is bot attack?
What is a web bot?
What is a ticket bot?
None of the above.

Now if user types a question similar to one of the above options it will respond with a wronganswer.
**Question:** When was web bot developed?
**QnAMaker Reply:** It will pick answer of question "What is a web bot?". Even if answer for "When was web bot developed?" exists in qnamaker service.

Thank you!

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
