### ISSUE TITLE
issue with QnA Maker with active learning - Node Js 

### ISSUE THREAD

**Issue by fraangel** [microsoft/BotBuilder-CognitiveServices#72]
##  Bot Info:

- SDK Platform: Node.js
- Deployment Environment: Auzure Bot Service, local development with Emulator

## Issue Description:

Hi all! I'm developing a chatbot using node Js and I want to enable active learning. I was reading this [article](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/guides/active-learning-qnamaker)  and I still runned the [code](https://github.com/Microsoft/BotBuilder-CognitiveServices/blob/master/Node/samples/QnAMaker/QnAMakerBotWithActiveLearning/app.js) posted but nothing happens. 
Is there any other procedure or code to run in order to enable active learning in my bot?  
Thanks in advance

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
