### ISSUE TITLE
Creating bot with QnA Maker

### ISSUE THREAD

**Issue by khalidmushtaq1987** [microsoft/BotBuilder-CognitiveServices#74]
Hi There,

I need help. I have created a basic QnA using QnA maker. I have also deployed this QnA in Azure. Now I would like to change default message when no good match is found in QnA maker, unfortunately I am unable to do so. I have read few articles and I got to know that I need to select my Bot name, then go to "build" option and choose the option of click online code editor. But when I click on this option it gives me an error message " Unable to open 'readme.md' for rendering. Please make sure the file exists and that it is a valid markdown file." Appreciate if anyone can help me to resolve my issue.

Thanks
Khalid

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
