### ISSUE TITLE
defaultMessage option should be a function for localization

### ISSUE THREAD

**Issue by howlowck** [microsoft/BotBuilder-CognitiveServices#75]
Currently it is not possible for the default message to be dynamic based on locale.  Ideally, the `defaultMessage` could either be a string or a function that takes in the session as the parameter.

**Comment by denisyfrolov** [comment]
@howlowck you can try this:

```c#
using System.Resources;
using Microsoft.Bot.Builder.CognitiveServices.QnAMaker;

[Serializable]
public class BasicQnAMakerDialog : QnAMakerDialog
{        
    public BasicQnAMakerDialog() : base(new QnAMakerService(new QnAMakerAttribute("key", "baseid", ResourceManager.CreateFileBasedResourceManager("baseName", "resourceDir", null).GetString("DefaultMessage"))))
    {
    }
}
```

**Comment by howlowck** [comment]
Thanks @denisyfrolov. I should add that this issue was originally filed for Nodejs. And there is currently a similar proposal for C# (issue: #87)

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
