### ISSUE TITLE
Encoding problems in questionOptions 

### ISSUE THREAD

**Issue by vinisants** [microsoft/BotBuilder-CognitiveServices#77]
Hello,

I'm using botbuilder@3.14.0 and botbuilder-cognitiveservices@1.1.0, and I have a problem with special characters (encoding) of questions like "Onde faço o pagamento do meu pedido?" (Where do I pay for my order?).

Here a print screen when I'm testing it in Bot Framework Emulator:
<img width="952" alt="bot8" src="https://user-images.githubusercontent.com/32205109/36005172-82ed90d6-0d1d-11e8-8807-e72276c2c11d.PNG">

I have tried this solution but not worked (utf8.decode). 
<img width="944" alt="bot7" src="https://user-images.githubusercontent.com/32205109/36005062-f6addb12-0d1c-11e8-9387-d9962331735b.PNG">

And I have tried also other libs like fix-utf8 and windows-1232.

Just to compare, when I'm using the C# version (BotBuilder 3.13.1 and Cognitive 1.1.2), the problem did not exists:

<img width="950" alt="bot9" src="https://user-images.githubusercontent.com/32205109/36005418-ce2b3e8a-0d1e-11e8-82cb-3830379d533f.PNG">

**Comment by vinisants** [comment]
Hello!!!!

After looking another classes I have used the same decode (htmlentities.decode) existing in QnAMakerRecognizer and its working!

I will send the code below, and suggest you guys change it for next version :)

<img width="835" alt="bot10" src="https://user-images.githubusercontent.com/32205109/36007022-8f8bb71e-0d27-11e8-8297-4c287feeabb9.PNG">

**Comment by vitoravale** [comment]
The package available in [npm](https://www.npmjs.com/package/botbuilder-cognitiveservices) is outdated, there's already a solution for this question on changes of  PR #45

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
