### ISSUE TITLE
Compile error re: IScorable when referencing QnAMakerScorable.

### ISSUE THREAD

**Issue by jorupp** [microsoft/BotBuilder-CognitiveServices#8]
When building my app using Microsoft.Bot.Builder 3.5.3 and Microsoft.Bot.Builder.CognitiveServices 1.0.2 (both from nuget), and try to use QnAMakerScorable, I get this error:

```Reference to type 'IScorable<,>' claims it is defined in 'Microsoft.Bot.Builder', but it could not be found```

It looks like Microsoft.Bot.Builder.CognitiveServices was built against an old (3.3?) Bot.Builder assembly?  Are there plans to update it for the new one?

**Comment by willportnoy** [comment]
Yes, we're planning on a release in a few days, as far as I know.

@Andrea-Orimoto for fyi

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
