### ISSUE TITLE
QnAMakerDialog.js should handle begin method

### ISSUE THREAD

**Issue by rjrahul** [Microsoft/BotBuilder-CognitiveServices#81]
**Use case**
* Use QnAMaker recognizer as 1 of the recognizer in IntentDialog along with a custom recognizer

**Problem**
Post recognition an intent is triggered from `IntentDialog.prototype.invokeIntent` method, the call goes to `session.beginDialog` that in turn sends call to `dialog.begin` with 2 arguments `(session, recognizeResult)`.

Since QnAMakerDialog does not have a begin method it defaults to its parent Dialog class. This class does not pass the recognizeResult to replyReceived method.

This causes QnAMaker to be fired twice for same request and thereby affecting the rate limit & pricing (in future). We should have QnAMakerDialog to override begin method as below to handle the recognizeResult

```
QnAMakerDialog.prototype.begin = function(session, recognizeResult) {
    this.replyReceived(session, recognizeResult);
}
```

**Comment by stevkan** [comment]
Merged.
