### ISSUE TITLE
Feedback library options are truncated so it's not obvious which question to choose.

### ISSUE THREAD

**Issue by chearmstrong** [microsoft/BotBuilder-CognitiveServices#83]
Hi,

I'm using the QnA maker feedback library with the Bot Framework. However, when a definitive answer isn't found and it lists the possibilities for a user to choose, the questions are truncated (the test is cut off). This means the user isn't sure which question to choose.

Is this a bug/issue? Is there any way to fix this?

My bot is deployed to Facebook Messenger.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
