### ISSUE TITLE
Bot Framework LUIS and QNA integration

### ISSUE THREAD

**Issue by saravana13** [microsoft/BotBuilder-CognitiveServices#85]
We are building a chat bot with LUIS and QNA in c#. The approach is like when nointent is reached in LUIS it will invoke QNA maker and try to see if the asked question is available there or not . But if QNA mathes the asked question with multiple Question in knowledge base it will prompt with all such question and ask what the user actually meant. But the problem is when user selects any one of the question some times it matches any of my luis intents there by displaying wrong answer instead of going to QNA maker.

I was available to fix this by assigning such questions to nointents in luis. But i just wanted to know whether this is right approach or something else can be done for this. Because it will be pain to actually sit and assign all such possible questions to nointents.

If some one else has approached this in different, please educate me with your approach.

Thanks in advance

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
