### ISSUE TITLE
issue with ActiveLearning for QnA Maker.

### ISSUE THREAD

**Issue by Chitma** [microsoft/BotBuilder-CognitiveServices#88]
Hi Team,

I just tried using active learning provided by Qna Maker, but the request ended up with "**The remote server returned an error: (404) Not Found**." Error.

I have crosschecked my subscription key and knowleadge base id. I am trying to post the json string(please find below).

```
public async Task TrainQnA(string jsonString)
        {
            var _responseString = string.Empty;

            Uri qnamakerUriBase = new Uri("https://westus.api.cognitive.microsoft.com/qnamaker/v2.0");
            var builder = new UriBuilder($"{qnamakerUriBase}/knowledgebases/{_knowleadgeBaseID}/train");

            //Add the question as part of the body
            try
            {
                //Send the POST request
                using (WebClient client = new WebClient())
                {
                    //Add the subscription key header
                    client.Headers.Add("Ocp-Apim-Subscription-Key", _subscriptionKey);
                    client.Headers.Add("Content-Type", "application/json");
                    client.Headers.Add("Accept", "application/json");
                    _responseString = client.UploadString(builder.Uri, jsonString.ToString());
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
  }
```

Here is the Json:

`{"feedbackRecords": [{"userId": "1","userQuestion": "hey","kbQuestion": "hi","kbAnswer": "hey"}]}`

**Comment by PhantasmNZ** [comment]
it doesn't work.  Microsoft killed it for GA.
https://github.com/Microsoft/BotBuilder-CognitiveServices/issues/106

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
