### ISSUE TITLE
matching entity throwing InvalidCastException when using Custom List Entities in ActionBinding

### ISSUE THREAD

**Issue by SunKyungCho** [microsoft/BotBuilder-CognitiveServices#89]
## Bot Info
* SDK Platform: C#
* Deployment Environment: local development with Emulator

## Issue Description

I'm working on a prototype app bot using the LUIS action binding. I use LUIS list type entity. There was a problem with that. 

## Code Example

LuisActionResolver.cs (line :520~)
```csharp
    // Prioritize resolution
    if (matchingEntity != null)
    {
        var paramValue = matchingEntity.Resolution != null && matchingEntity.Resolution.Count > 0
                  ? matchingEntity.Resolution.First().Value
                  : matchingEntity.Entity;
       // paramValue is returned type 'System.Collections.Generic.List<object>'
        result &= AssignValue(action, property, paramValue);
     }
```
 paramValue is returned type 'System.Collections.Generic.List<object>'

LuisActionResolver.cs (line:413~)
```csharp
private static object SanitizeInputValue(Type targetType, object value)
        {
            object result = value;

            // handle case where input is JArray returned from LUIS
           if (value is JArray) // false.  because, it's not 'Newtonsoft.Json.Linq.JArray'
            {
                var arrayOfValues = value as JArray;

                if (targetType.IsArray)
                {
                    result = arrayOfValues.AsEnumerable<object>();
                }
                else
                {
                    if (arrayOfValues.Count > 1)
                    {
                        throw new FormatException("Cannot assign multiple values to single field");
                    }

                    result = arrayOfValues[0];
                }
            }

            return result; // type : '{System.Collections.Generic.List<object>} '
        }
```
so, `if (value is JArray)` this code in this section is false. because, `value` is not 'Newtonsoft.Json.Linq.JArray'. it's `System.Collections.Generic.List<object>`

LuisActionResolver.cs (line : 356~)
```csharp
   paramValue = SanitizeInputValue(type, paramValue);

   if (type.IsArray)
   {
        value = BuildArrayOfValues(action, property, type.GetElementType(), paramValue);
   }
   else if (type.IsEnum)
   {
        value = Enum.Parse(type, paramValue.ToString());
   }
   else
   {
        value = Convert.ChangeType(paramValue, type);  //Exception here.
        //Exception message : Object must implement IConvertible.
   }
```
`type` is `string` . `paramValue` is  '{System.Collections.Generic.List<object>} ' I think this should be type string.

## Reproduction Steps
1. Register the list type entity in LUIS.
2. Just match the list entity by example.

## Actual Results

Exception message : Object must implement IConvertible.

**Comment by SunKyungCho** [comment]
I could create a pull request but I'm not sure if this is the best approach to solve the problem. #90

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
