### ISSUE TITLE
QnAMaker just terminates and throws me out of all dialogs in our bot

### ISSUE THREAD

**Issue by Old-T** [microsoft/BotBuilder-CognitiveServices#96]
Hi,
We have started to use QnAMaker in our Bot more during the recent test period. I have noticed that sometimes when we've called QnAMakerDialog a lot (5 - 10 calls per minute), everything just terminates and and throws me back to bot framwork main loop.
I've traced to see what happens and I can see that we call base(new QnAMakerService(new QnAMakerAttribute(..),...) but after the call we're back in the man loop again.
No exception, no errors no nothing.

We _might_ have reached the upper limit for the free QnAMaker server (we have applied to increase the limit) but even if we have, I still need to trap this and signal this either to the user or log the fact in the error log.

Anyone else seen this behavior?

// Tommy

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
