### ISSUE TITLE
Abillity to provide Cards if required LuisAction properties are missing.

### ISSUE THREAD

**Issue by Michaelvsk** [microsoft/BotBuilder-CognitiveServices#97]
Hi,

I am currently working on a chat bot using the C# Bot Framework and the LuisActionBinding extension found in this repository.
I have several LuisActions with properties marked as required. When the user invokes the actions but the utterance is missing required properties, I would like to show an adaptive card (as illustraded in [this examle](https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/cards-AdaptiveCards#outcome)) to let the user provide the values in a convenient way.

The Attributes `LuisActionBinding` and `LuisActionBindingParam` do not seem to offer such functionality. Am I correct that that scenario is currently not supported?

Best Regards,
Michael

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
