### ISSUE TITLE
QnAMaker Exception when multiple Services are provided and at least 1 with no answer and 1 with an answer

### ISSUE THREAD

**Issue by nrobert** [microsoft/BotBuilder-CognitiveServices#99]
I noticed a crash in `QnAMakerDialog` in a specific case:
- several QnAMaker KB are declared (called service1 and service2 after in this issue)
- for a given question, one of the services has an answer and the other does not have an answer

In that case, the code breaks on this [line](https://github.com/Microsoft/BotBuilder-CognitiveServices/blob/master/CSharp/Library/QnAMaker/QnAMaker/QnAMakerDialog.cs#L99):
`var maxValue = tasks.Max(x => x.Result.Answers[0].Score);`
Because the service with no reply is an item of `tasks` with a `Result` that has an empty `Answers`

StackOverflow issue where I pointed that: https://stackoverflow.com/questions/50132206/multiple-qna-service-in-one-bot-using-c-sharp/50133978

**How to reproduce:**

Create 2 KB with different questions and try one of the questions in a dialog pointing to those 2 KBs

```C#
[Serializable]
[QnAMaker("QnaSubscriptionKey1", "QnaKnowledgebaseId1", "Hmm, I wasn't able to find an article about that. Can you try asking in a different way?", 0.50, 3)]
[QnAMaker("QnaSubscriptionKey2", "QnaKnowledgebaseId2", "Hmm, I wasn't able to find an article about that. Can you try asking in a different way?", 0.5, 3)]
public class RootDialog : QnAMakerDialog
{
}
```

**Comment by nrobert** [comment]
Got a fix, I will make a Pull Request soon

**Comment by JasonSowers** [comment]
@nrobert I have made the appropriate people aware of your pull request, thank you for the contribution 👍

**Comment by nrobert** [comment]
Great @JasonSowers , thanks

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
